import { lazy, type ComponentType } from "react";
import type { TemplateProps } from "./types";

export const templateComponents: Record<string, ComponentType<TemplateProps>> = {
  "10-brutalist": lazy(() => import("./Template10Brutalist")),
  "1-clean": lazy(() => import("./Template1Clean")),
  "2-cinematic": lazy(() => import("./Template2Cinematic")),
  "3-editorial": lazy(() => import("./Template3Editorial")),
  "4-instagram": lazy(() => import("./Template4Instagram")),
  "5-masonry": lazy(() => import("./Template5Masonry")),
  "6-split": lazy(() => import("./Template6Split")),
  "7-vertical": lazy(() => import("./Template7Vertical")),
  "8-carousel": lazy(() => import("./Template8Carousel")),
  "9-story-cards": lazy(() => import("./Template9StoryCards")),
  "beauty-barber": lazy(() => import("./TemplateBeautyBarber")),
  "beauty-brow": lazy(() => import("./TemplateBeautyBrow")),
  "beauty-hair": lazy(() => import("./TemplateBeautyHair")),
  "beauty-lash": lazy(() => import("./TemplateBeautyLash")),
  "beauty-makeup": lazy(() => import("./TemplateBeautyMakeup")),
  "beauty-nails": lazy(() => import("./TemplateBeautyNails")),
  "beauty-piercing": lazy(() => import("./TemplateBeautyPiercing")),
  "beauty-skin": lazy(() => import("./TemplateBeautySkin")),
  "beauty-spa": lazy(() => import("./TemplateBeautySpa")),
  "beauty-stylist": lazy(() => import("./TemplateBeautyStylist")),
  "beauty-tan": lazy(() => import("./TemplateBeautyTan")),
  "beauty-tattoo": lazy(() => import("./TemplateBeautyTattoo")),
  "childcare-babysitter": lazy(() => import("./TemplateChildcareBabysitter")),
  "childcare-consultant": lazy(() => import("./TemplateChildcareConsultant")),
  "childcare-daycare": lazy(() => import("./TemplateChildcareDaycare")),
  "childcare-disability": lazy(() => import("./TemplateChildcareDisability")),
  "childcare-doula": lazy(() => import("./TemplateChildcareDoula")),
  "childcare-elder": lazy(() => import("./TemplateChildcareElder")),
  "childcare-nanny": lazy(() => import("./TemplateChildcareNanny")),
  "childcare-parenting": lazy(() => import("./TemplateChildcareParenting")),
  "childcare-senior": lazy(() => import("./TemplateChildcareSenior")),
  "childcare-sleep": lazy(() => import("./TemplateChildcareSleep")),
  "coaching-a-d-h-d": lazy(() => import("./TemplateCoachingADHD")),
  "coaching-business": lazy(() => import("./TemplateCoachingBusiness")),
  "coaching-career": lazy(() => import("./TemplateCoachingCareer")),
  "coaching-executive": lazy(() => import("./TemplateCoachingExecutive")),
  "coaching-fitness-mind": lazy(() => import("./TemplateCoachingFitnessMind")),
  "coaching-leadership": lazy(() => import("./TemplateCoachingLeadership")),
  "coaching-life": lazy(() => import("./TemplateCoachingLife")),
  "coaching-parent": lazy(() => import("./TemplateCoachingParent")),
  "coaching-productivity": lazy(() => import("./TemplateCoachingProductivity")),
  "coaching-relationship": lazy(() => import("./TemplateCoachingRelationship")),
  "corporate-pro": lazy(() => import("./TemplateCorporatePro")),
  "corporate-suite": lazy(() => import("./TemplateCorporateSuite")),
  "creative-architect": lazy(() => import("./TemplateCreativeArchitect")),
  "creative-artist": lazy(() => import("./TemplateCreativeArtist")),
  "creative-copywriter": lazy(() => import("./TemplateCreativeCopywriter")),
  "creative-editor": lazy(() => import("./TemplateCreativeEditor")),
  "creative-graphic": lazy(() => import("./TemplateCreativeGraphic")),
  "creative-illustrator": lazy(() => import("./TemplateCreativeIllustrator")),
  "creative-interior": lazy(() => import("./TemplateCreativeInterior")),
  "creative-musician": lazy(() => import("./TemplateCreativeMusician")),
  "creative-photographer": lazy(() => import("./TemplateCreativePhotographer")),
  "creative-u-x": lazy(() => import("./TemplateCreativeUX")),
  "creative-videographer": lazy(() => import("./TemplateCreativeVideographer")),
  "creative-voice": lazy(() => import("./TemplateCreativeVoice")),
  "creative-web-dev": lazy(() => import("./TemplateCreativeWebDev")),
  "creative-writer": lazy(() => import("./TemplateCreativeWriter")),
  "engagement-blush": lazy(() => import("./TemplateEngagementBlush")),
  "engagement-elegant": lazy(() => import("./TemplateEngagementElegant")),
  "event-balloon": lazy(() => import("./TemplateEventBalloon")),
  "event-caterer": lazy(() => import("./TemplateEventCaterer")),
  "event-d-j": lazy(() => import("./TemplateEventDJ")),
  "event-florist": lazy(() => import("./TemplateEventFlorist")),
  "event-makeup": lazy(() => import("./TemplateEventMakeup")),
  "event-officiant": lazy(() => import("./TemplateEventOfficiant")),
  "event-photographer": lazy(() => import("./TemplateEventPhotographer")),
  "event-planner": lazy(() => import("./TemplateEventPlanner")),
  "event-rentals": lazy(() => import("./TemplateEventRentals")),
  "event-venue": lazy(() => import("./TemplateEventVenue")),
  "event-videographer": lazy(() => import("./TemplateEventVideographer")),
  "event-wedding-planner": lazy(() => import("./TemplateEventWeddingPlanner")),
  "fall-palette": lazy(() => import("./TemplateFallPalette")),
  "fall-warmth": lazy(() => import("./TemplateFallWarmth")),
  "family-modern": lazy(() => import("./TemplateFamilyModern")),
  "family-warm": lazy(() => import("./TemplateFamilyWarm")),
  "fitness-dance": lazy(() => import("./TemplateFitnessDance")),
  "fitness-martial-arts": lazy(() => import("./TemplateFitnessMartialArts")),
  "fitness-meditation": lazy(() => import("./TemplateFitnessMeditation")),
  "fitness-pilates": lazy(() => import("./TemplateFitnessPilates")),
  "fitness-sports-coach": lazy(() => import("./TemplateFitnessSportsCoach")),
  "fitness-trainer": lazy(() => import("./TemplateFitnessTrainer")),
  "fitness-wellness": lazy(() => import("./TemplateFitnessWellness")),
  "fitness-yoga": lazy(() => import("./TemplateFitnessYoga")),
  "golden-feast": lazy(() => import("./TemplateGoldenFeast")),
  "holiday-elegant": lazy(() => import("./TemplateHolidayElegant")),
  "holiday-festive": lazy(() => import("./TemplateHolidayFestive")),
  "holiday-hearth": lazy(() => import("./TemplateHolidayHearth")),
  "home-cleaning": lazy(() => import("./TemplateHomeCleaning")),
  "home-contractor": lazy(() => import("./TemplateHomeContractor")),
  "home-electrician": lazy(() => import("./TemplateHomeElectrician")),
  "home-h-v-a-c": lazy(() => import("./TemplateHomeHVAC")),
  "home-handyman": lazy(() => import("./TemplateHomeHandyman")),
  "home-junk": lazy(() => import("./TemplateHomeJunk")),
  "home-landscape": lazy(() => import("./TemplateHomeLandscape")),
  "home-moving": lazy(() => import("./TemplateHomeMoving")),
  "home-painter": lazy(() => import("./TemplateHomePainter")),
  "home-pest": lazy(() => import("./TemplateHomePest")),
  "home-plumber": lazy(() => import("./TemplateHomePlumber")),
  "home-pool": lazy(() => import("./TemplateHomePool")),
  "home-roofing": lazy(() => import("./TemplateHomeRoofing")),
  "home-security": lazy(() => import("./TemplateHomeSecurity")),
  "home-solar": lazy(() => import("./TemplateHomeSolar")),
  "influencer-author": lazy(() => import("./TemplateInfluencerAuthor")),
  "influencer-blogger": lazy(() => import("./TemplateInfluencerBlogger")),
  "influencer-brand": lazy(() => import("./TemplateInfluencerBrand")),
  "influencer-creator": lazy(() => import("./TemplateInfluencerCreator")),
  "influencer-mom": lazy(() => import("./TemplateInfluencerMom")),
  "influencer-newsletter": lazy(() => import("./TemplateInfluencerNewsletter")),
  "influencer-podcast": lazy(() => import("./TemplateInfluencerPodcast")),
  "influencer-speaker": lazy(() => import("./TemplateInfluencerSpeaker")),
  "influencer-streamer": lazy(() => import("./TemplateInfluencerStreamer")),
  "influencer-thought": lazy(() => import("./TemplateInfluencerThought")),
  "influencer-tik-tok": lazy(() => import("./TemplateInfluencerTikTok")),
  "influencer-you-tube": lazy(() => import("./TemplateInfluencerYouTube")),
  "legal-attorney": lazy(() => import("./TemplateLegalAttorney")),
  "legal-bookkeeper": lazy(() => import("./TemplateLegalBookkeeper")),
  "legal-broker": lazy(() => import("./TemplateLegalBroker")),
  "legal-c-p-a": lazy(() => import("./TemplateLegalCPA")),
  "legal-consultant": lazy(() => import("./TemplateLegalConsultant")),
  "legal-estate": lazy(() => import("./TemplateLegalEstate")),
  "legal-h-r": lazy(() => import("./TemplateLegalHR")),
  "legal-immigration": lazy(() => import("./TemplateLegalImmigration")),
  "legal-insurance": lazy(() => import("./TemplateLegalInsurance")),
  "legal-mediator": lazy(() => import("./TemplateLegalMediator")),
  "legal-mortgage": lazy(() => import("./TemplateLegalMortgage")),
  "legal-notary": lazy(() => import("./TemplateLegalNotary")),
  "legal-tax": lazy(() => import("./TemplateLegalTax")),
  "legal-wealth": lazy(() => import("./TemplateLegalWealth")),
  "marketing-ads": lazy(() => import("./TemplateMarketingAds")),
  "marketing-brand": lazy(() => import("./TemplateMarketingBrand")),
  "marketing-content": lazy(() => import("./TemplateMarketingContent")),
  "marketing-digital": lazy(() => import("./TemplateMarketingDigital")),
  "marketing-ecommerce": lazy(() => import("./TemplateMarketingEcommerce")),
  "marketing-email": lazy(() => import("./TemplateMarketingEmail")),
  "marketing-funnel": lazy(() => import("./TemplateMarketingFunnel")),
  "marketing-p-r": lazy(() => import("./TemplateMarketingPR")),
  "marketing-s-e-o": lazy(() => import("./TemplateMarketingSEO")),
  "marketing-social": lazy(() => import("./TemplateMarketingSocial")),
  "marketing-website": lazy(() => import("./TemplateMarketingWebsite")),
  "medical-acupuncture": lazy(() => import("./TemplateMedicalAcupuncture")),
  "medical-chiro": lazy(() => import("./TemplateMedicalChiro")),
  "medical-dentist": lazy(() => import("./TemplateMedicalDentist")),
  "medical-derma": lazy(() => import("./TemplateMedicalDerma")),
  "medical-doctor": lazy(() => import("./TemplateMedicalDoctor")),
  "medical-massage": lazy(() => import("./TemplateMedicalMassage")),
  "medical-nutrition": lazy(() => import("./TemplateMedicalNutrition")),
  "medical-o-t": lazy(() => import("./TemplateMedicalOT")),
  "medical-optom": lazy(() => import("./TemplateMedicalOptom")),
  "medical-ortho": lazy(() => import("./TemplateMedicalOrtho")),
  "medical-p-t": lazy(() => import("./TemplateMedicalPT")),
  "medical-psych": lazy(() => import("./TemplateMedicalPsych")),
  "medical-psychiatry": lazy(() => import("./TemplateMedicalPsychiatry")),
  "medical-specialist": lazy(() => import("./TemplateMedicalSpecialist")),
  "medical-speech": lazy(() => import("./TemplateMedicalSpeech")),
  "medical-telehealth": lazy(() => import("./TemplateMedicalTelehealth")),
  "medical-therapy": lazy(() => import("./TemplateMedicalTherapy")),
  "office-art": lazy(() => import("./TemplateOfficeArt")),
  "office-beauty": lazy(() => import("./TemplateOfficeBeauty")),
  "office-conference": lazy(() => import("./TemplateOfficeConference")),
  "office-cowork": lazy(() => import("./TemplateOfficeCowork")),
  "office-dance": lazy(() => import("./TemplateOfficeDance")),
  "office-event": lazy(() => import("./TemplateOfficeEvent")),
  "office-music": lazy(() => import("./TemplateOfficeMusic")),
  "office-photo": lazy(() => import("./TemplateOfficePhoto")),
  "office-podcast": lazy(() => import("./TemplateOfficePodcast")),
  "office-private": lazy(() => import("./TemplateOfficePrivate")),
  "office-therapy": lazy(() => import("./TemplateOfficeTherapy")),
  "pet-boarding": lazy(() => import("./TemplatePetBoarding")),
  "pet-daycare": lazy(() => import("./TemplatePetDaycare")),
  "pet-groomer": lazy(() => import("./TemplatePetGroomer")),
  "pet-mobile-vet": lazy(() => import("./TemplatePetMobileVet")),
  "pet-photographer": lazy(() => import("./TemplatePetPhotographer")),
  "pet-sitter": lazy(() => import("./TemplatePetSitter")),
  "pet-trainer": lazy(() => import("./TemplatePetTrainer")),
  "pet-vet": lazy(() => import("./TemplatePetVet")),
  "pet-walker": lazy(() => import("./TemplatePetWalker")),
  "portrait-headshot": lazy(() => import("./TemplatePortraitHeadshot")),
  "portrait-studio": lazy(() => import("./TemplatePortraitStudio")),
  "real-estate-agent": lazy(() => import("./TemplateRealEstateAgent")),
  "real-estate-appraiser": lazy(() => import("./TemplateRealEstateAppraiser")),
  "real-estate-inspector": lazy(() => import("./TemplateRealEstateInspector")),
  "real-estate-investor": lazy(() => import("./TemplateRealEstateInvestor")),
  "real-estate-leasing": lazy(() => import("./TemplateRealEstateLeasing")),
  "real-estate-luxury": lazy(() => import("./TemplateRealEstateLuxury")),
  "real-estate-mortgage": lazy(() => import("./TemplateRealEstateMortgage")),
  "real-estate-property": lazy(() => import("./TemplateRealEstateProperty")),
  "restaurant-bakery": lazy(() => import("./TemplateRestaurantBakery")),
  "restaurant-bar": lazy(() => import("./TemplateRestaurantBar")),
  "restaurant-cafe": lazy(() => import("./TemplateRestaurantCafe")),
  "restaurant-casual": lazy(() => import("./TemplateRestaurantCasual")),
  "restaurant-catering": lazy(() => import("./TemplateRestaurantCatering")),
  "restaurant-chef": lazy(() => import("./TemplateRestaurantChef")),
  "restaurant-coffee": lazy(() => import("./TemplateRestaurantCoffee")),
  "restaurant-dessert": lazy(() => import("./TemplateRestaurantDessert")),
  "restaurant-fine": lazy(() => import("./TemplateRestaurantFine")),
  "restaurant-juice": lazy(() => import("./TemplateRestaurantJuice")),
  "restaurant-meal-prep": lazy(() => import("./TemplateRestaurantMealPrep")),
  "restaurant-popup": lazy(() => import("./TemplateRestaurantPopup")),
  "restaurant-truck": lazy(() => import("./TemplateRestaurantTruck")),
  "retail-book": lazy(() => import("./TemplateRetailBook")),
  "retail-fashion": lazy(() => import("./TemplateRetailFashion")),
  "retail-florist": lazy(() => import("./TemplateRetailFlorist")),
  "retail-food": lazy(() => import("./TemplateRetailFood")),
  "retail-furniture": lazy(() => import("./TemplateRetailFurniture")),
  "retail-gallery": lazy(() => import("./TemplateRetailGallery")),
  "retail-gift": lazy(() => import("./TemplateRetailGift")),
  "retail-jeweler": lazy(() => import("./TemplateRetailJeweler")),
  "retail-maker": lazy(() => import("./TemplateRetailMaker")),
  "retail-pet": lazy(() => import("./TemplateRetailPet")),
  "retail-toy": lazy(() => import("./TemplateRetailToy")),
  "retail-vintage": lazy(() => import("./TemplateRetailVintage")),
  "specialty-astrologer": lazy(() => import("./TemplateSpecialtyAstrologer")),
  "specialty-genealogist": lazy(() => import("./TemplateSpecialtyGenealogist")),
  "specialty-grant": lazy(() => import("./TemplateSpecialtyGrant")),
  "specialty-interpreter": lazy(() => import("./TemplateSpecialtyInterpreter")),
  "specialty-p-i": lazy(() => import("./TemplateSpecialtyPI")),
  "specialty-religious": lazy(() => import("./TemplateSpecialtyReligious")),
  "specialty-researcher": lazy(() => import("./TemplateSpecialtyResearcher")),
  "specialty-speaker": lazy(() => import("./TemplateSpecialtySpeaker")),
  "specialty-spiritual": lazy(() => import("./TemplateSpecialtySpiritual")),
  "specialty-translator": lazy(() => import("./TemplateSpecialtyTranslator")),
  "sports-action": lazy(() => import("./TemplateSportsAction")),
  "sports-editorial": lazy(() => import("./TemplateSportsEditorial")),
  "spring-blossom": lazy(() => import("./TemplateSpringBlossom")),
  "spring-fresh": lazy(() => import("./TemplateSpringFresh")),
  "street-gritty": lazy(() => import("./TemplateStreetGritty")),
  "street-neon": lazy(() => import("./TemplateStreetNeon")),
  "summer-beach": lazy(() => import("./TemplateSummerBeach")),
  "summer-golden": lazy(() => import("./TemplateSummerGolden")),
  "teaching-acting": lazy(() => import("./TemplateTeachingActing")),
  "teaching-admissions": lazy(() => import("./TemplateTeachingAdmissions")),
  "teaching-art": lazy(() => import("./TemplateTeachingArt")),
  "teaching-coding": lazy(() => import("./TemplateTeachingCoding")),
  "teaching-course": lazy(() => import("./TemplateTeachingCourse")),
  "teaching-debate": lazy(() => import("./TemplateTeachingDebate")),
  "teaching-driving": lazy(() => import("./TemplateTeachingDriving")),
  "teaching-homeschool": lazy(() => import("./TemplateTeachingHomeschool")),
  "teaching-language": lazy(() => import("./TemplateTeachingLanguage")),
  "teaching-music": lazy(() => import("./TemplateTeachingMusic")),
  "teaching-test-prep": lazy(() => import("./TemplateTeachingTestPrep")),
  "teaching-tutor": lazy(() => import("./TemplateTeachingTutor")),
  "teaching-writing": lazy(() => import("./TemplateTeachingWriting")),
  "tech-a-i": lazy(() => import("./TemplateTechAI")),
  "tech-app": lazy(() => import("./TemplateTechApp")),
  "tech-automation": lazy(() => import("./TemplateTechAutomation")),
  "tech-cyber": lazy(() => import("./TemplateTechCyber")),
  "tech-data": lazy(() => import("./TemplateTechData")),
  "tech-i-t": lazy(() => import("./TemplateTechIT")),
  "tech-no-code": lazy(() => import("./TemplateTechNoCode")),
  "tech-product": lazy(() => import("./TemplateTechProduct")),
  "tech-software": lazy(() => import("./TemplateTechSoftware")),
  "tech-support": lazy(() => import("./TemplateTechSupport")),
  "travel-agent": lazy(() => import("./TemplateTravelAgent")),
  "travel-airbnb": lazy(() => import("./TemplateTravelAirbnb")),
  "travel-bn-b": lazy(() => import("./TemplateTravelBnB")),
  "travel-consultant": lazy(() => import("./TemplateTravelConsultant")),
  "travel-experience": lazy(() => import("./TemplateTravelExperience")),
  "travel-guide": lazy(() => import("./TemplateTravelGuide")),
  "travel-hotel": lazy(() => import("./TemplateTravelHotel")),
  "travel-retreat": lazy(() => import("./TemplateTravelRetreat")),
  "winter-cozy": lazy(() => import("./TemplateWinterCozy")),
  "winter-frozen": lazy(() => import("./TemplateWinterFrozen")),
};

export { TEMPLATE_REGISTRY } from "./types";
export type { TemplateProps, TemplateInfo } from "./types";

/**
 * Legacy template IDs from before the numeric-kebab rename.
 * Old gallery_config rows in D1 may still store these values.
 */
export const LEGACY_TEMPLATE_ALIASES: Record<string, string> = {
  "clean-minimal": "1-clean",
  "cinematic-dark": "2-cinematic",
  "editorial-magazine": "3-editorial",
  "instagram-grid": "4-instagram",
  "masonry-wall": "5-masonry",
  "split-hero": "6-split",
  "vertical-scroll": "7-vertical",
  "carousel-spotlight": "8-carousel",
  "story-cards": "9-story-cards",
  "brutalist-bold": "10-brutalist",
};

/** Resolve a stored template id to a registry key, mapping legacy names to canonical IDs. */
export function resolveTemplateId(id?: string | null): string {
  if (!id) return "1-clean";
  if (templateComponents[id]) return id;
  return LEGACY_TEMPLATE_ALIASES[id] ?? "1-clean";
}
