/** Shared types for all photographer profile templates */

export interface TemplateProps {
  name: string;
  tagline: string;
  specialties: string[];
  bio: string;
  website: string;
  serviceArea: string;
  verified: boolean;
  pricing: { downloads?: { single?: number; full?: number } };
  portfolio: { id: string; url: string; filename: string }[];
  onHire: () => void;
  onPhotoClick: (index: number) => void;
  colorScheme?: { bg: string; text: string; accent: string };
  fontPairing?: { heading: string; body: string };
}

export interface TemplateInfo {
  id: string;
  name: string;
  category: string;
  description: string;
}

/** All available templates — add new ones here */
export const TEMPLATE_REGISTRY: TemplateInfo[] = [
  // Base templates
  { id: "10-brutalist", name: "Brutalist Bold", category: "base", description: "Huge text, stark B&W" },
  { id: "1-clean", name: "Clean Minimal", category: "base", description: "White, grid, simple" },
  { id: "2-cinematic", name: "Cinematic Dark", category: "base", description: "Black + gold, hero overlay" },
  { id: "3-editorial", name: "Editorial Magazine", category: "base", description: "Off-white, serif, asymmetric" },
  { id: "4-instagram", name: "Instagram Grid", category: "base", description: "Social-style, tight 3-col" },
  { id: "5-masonry", name: "Masonry Wall", category: "base", description: "Pinterest-style, varied heights" },
  { id: "6-split", name: "Split Hero", category: "base", description: "Half photo, half text" },
  { id: "7-vertical", name: "Vertical Scroll", category: "base", description: "Full-width stacked photos" },
  { id: "8-carousel", name: "Carousel Spotlight", category: "base", description: "One large photo + arrows" },
  { id: "9-story-cards", name: "Story Cards", category: "base", description: "Warm cards with titles" },
  // Beauty
  { id: "beauty-barber", name: "Barber Studio", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-brow", name: "Brow & Lash Bar", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-hair", name: "Hair Studio", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-lash", name: "Lash Lounge", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-makeup", name: "Makeup Artist", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-nails", name: "Nail Studio", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-piercing", name: "Piercing Studio", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-skin", name: "Skin Clinic", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-spa", name: "Spa Retreat", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-stylist", name: "Fashion Stylist", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-tan", name: "Tanning Studio", category: "beauty", description: "Beauty pro, portfolio showcase" },
  { id: "beauty-tattoo", name: "Tattoo Parlor", category: "beauty", description: "Beauty pro, portfolio showcase" },
  // Childcare
  { id: "childcare-babysitter", name: "Babysitter Profile", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-consultant", name: "Childcare Consultant", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-daycare", name: "Daycare Center", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-disability", name: "Disability Support", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-doula", name: "Doula Services", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-elder", name: "Elder Companion", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-nanny", name: "Nanny Profile", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-parenting", name: "Parenting Coach", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-senior", name: "Senior Care", category: "childcare", description: "Childcare services, warm and trusted" },
  { id: "childcare-sleep", name: "Sleep Consultant", category: "childcare", description: "Childcare services, warm and trusted" },
  // Coaching
  { id: "coaching-a-d-h-d", name: "ADHD Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-business", name: "Business Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-career", name: "Career Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-executive", name: "Executive Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-fitness-mind", name: "Fitness Mind Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-leadership", name: "Leadership Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-life", name: "Life Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-parent", name: "Parent Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-productivity", name: "Productivity Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  { id: "coaching-relationship", name: "Relationship Coaching", category: "coaching", description: "Coaching expertise, transformation" },
  // Corporate
  { id: "corporate-pro", name: "Conference Pro", category: "corporate", description: "Light gray, blue, professional" },
  { id: "corporate-suite", name: "Executive Suite", category: "corporate", description: "Dark navy, silver, authority" },
  // Creative
  { id: "creative-architect", name: "Architect Portfolio", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-artist", name: "Artist Portfolio", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-copywriter", name: "Copywriter Portfolio", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-editor", name: "Editor Portfolio", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-graphic", name: "Graphic Designer", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-illustrator", name: "Illustrator Portfolio", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-interior", name: "Interior Designer", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-musician", name: "Musician Profile", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-photographer", name: "Photographer Portfolio", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-u-x", name: "UX Designer", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-videographer", name: "Videographer Portfolio", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-voice", name: "Voice Artist", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-web-dev", name: "Web Developer", category: "creative", description: "Creative portfolio, project showcase" },
  { id: "creative-writer", name: "Writer Portfolio", category: "creative", description: "Creative portfolio, project showcase" },
  // Engagement
  { id: "engagement-blush", name: "Romantic Blush", category: "engagement", description: "Soft pink, script font, dreamy" },
  { id: "engagement-elegant", name: "Elegant Proposal", category: "engagement", description: "Cream, serif, luxury" },
  // Events
  { id: "event-balloon", name: "Balloon Artist", category: "events", description: "Event services, celebration showcase" },
  { id: "event-caterer", name: "Event Caterer", category: "events", description: "Event services, celebration showcase" },
  { id: "event-d-j", name: "DJ Services", category: "events", description: "Event services, celebration showcase" },
  { id: "event-florist", name: "Event Florist", category: "events", description: "Event services, celebration showcase" },
  { id: "event-makeup", name: "Event Makeup Artist", category: "events", description: "Event services, celebration showcase" },
  { id: "event-officiant", name: "Wedding Officiant", category: "events", description: "Event services, celebration showcase" },
  { id: "event-photographer", name: "Event Photographer", category: "events", description: "Event services, celebration showcase" },
  { id: "event-planner", name: "Event Planner", category: "events", description: "Event services, celebration showcase" },
  { id: "event-rentals", name: "Event Rentals", category: "events", description: "Event services, celebration showcase" },
  { id: "event-venue", name: "Event Venue", category: "events", description: "Event services, celebration showcase" },
  { id: "event-videographer", name: "Event Videographer", category: "events", description: "Event services, celebration showcase" },
  { id: "event-wedding-planner", name: "Wedding Planner", category: "events", description: "Event services, celebration showcase" },
  // Fall
  { id: "fall-palette", name: "Fall Palette", category: "fall", description: "Cream, autumn gradient strip" },
  { id: "fall-warmth", name: "Autumn Warmth", category: "fall", description: "Deep amber, cream, warm serif" },
  // Family
  { id: "family-modern", name: "Modern Family", category: "family", description: "Clean white, geometric, cheerful" },
  { id: "family-warm", name: "Warm Gathering", category: "family", description: "Earth tones, playful, scrapbook" },
  // Fitness
  { id: "fitness-dance", name: "Dance Instructor", category: "fitness", description: "Fitness training, strength and results" },
  { id: "fitness-martial-arts", name: "Martial Arts", category: "fitness", description: "Fitness training, strength and results" },
  { id: "fitness-meditation", name: "Meditation Guide", category: "fitness", description: "Fitness training, strength and results" },
  { id: "fitness-pilates", name: "Pilates Instructor", category: "fitness", description: "Fitness training, strength and results" },
  { id: "fitness-sports-coach", name: "Sports Coach", category: "fitness", description: "Fitness training, strength and results" },
  { id: "fitness-trainer", name: "Personal Trainer", category: "fitness", description: "Fitness training, strength and results" },
  { id: "fitness-wellness", name: "Wellness Coach", category: "fitness", description: "Fitness training, strength and results" },
  { id: "fitness-yoga", name: "Yoga Instructor", category: "fitness", description: "Fitness training, strength and results" },
  // Holiday Season
  { id: "golden-feast", name: "Golden Feast", category: "holiday-season", description: "Cream, amber, autumn harvest" },
  { id: "holiday-hearth", name: "Holiday Hearth", category: "holiday-season", description: "Cranberry, gold, festive" },
  // Holiday
  { id: "holiday-elegant", name: "Elegant Celebration", category: "holiday", description: "Champagne, gold sparkle" },
  { id: "holiday-festive", name: "Festive Pop", category: "holiday", description: "Bright, colorful, confetti" },
  // Home Services
  { id: "home-cleaning", name: "Cleaning Service", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-contractor", name: "General Contractor", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-electrician", name: "Electrician Pro", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-h-v-a-c", name: "HVAC Technician", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-handyman", name: "Handyman Service", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-junk", name: "Junk Removal", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-landscape", name: "Landscaping Pro", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-moving", name: "Moving Service", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-painter", name: "Painting Service", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-pest", name: "Pest Control", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-plumber", name: "Plumbing Service", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-pool", name: "Pool Service", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-roofing", name: "Roofing Contractor", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-security", name: "Security Systems", category: "home-services", description: "Home services, trusted professional" },
  { id: "home-solar", name: "Solar Installer", category: "home-services", description: "Home services, trusted professional" },
  // Influencer
  { id: "influencer-author", name: "Author Page", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-blogger", name: "Blogger Profile", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-brand", name: "Brand Ambassador", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-creator", name: "Content Creator", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-mom", name: "Mom Influencer", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-newsletter", name: "Newsletter Creator", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-podcast", name: "Podcast Host", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-speaker", name: "Public Speaker", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-streamer", name: "Streamer Channel", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-thought", name: "Thought Leader", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-tik-tok", name: "TikTok Creator", category: "influencer", description: "Social creator, content showcase" },
  { id: "influencer-you-tube", name: "YouTube Creator", category: "influencer", description: "Social creator, content showcase" },
  // Legal
  { id: "legal-attorney", name: "Attorney Profile", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-bookkeeper", name: "Bookkeeper Profile", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-broker", name: "Broker Profile", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-c-p-a", name: "CPA Profile", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-consultant", name: "Legal Consultant", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-estate", name: "Estate Planning", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-h-r", name: "HR Consultant", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-immigration", name: "Immigration Attorney", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-insurance", name: "Insurance Agent", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-mediator", name: "Mediator Profile", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-mortgage", name: "Mortgage Broker", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-notary", name: "Notary Public", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-tax", name: "Tax Professional", category: "legal", description: "Legal services, trust and authority" },
  { id: "legal-wealth", name: "Wealth Manager", category: "legal", description: "Legal services, trust and authority" },
  // Marketing
  { id: "marketing-ads", name: "Ads Specialist", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-brand", name: "Brand Strategist", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-content", name: "Content Marketer", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-digital", name: "Digital Marketer", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-ecommerce", name: "E-Commerce Marketer", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-email", name: "Email Marketer", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-funnel", name: "Funnel Builder", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-p-r", name: "PR Specialist", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-s-e-o", name: "SEO Specialist", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-social", name: "Social Media Manager", category: "marketing", description: "Marketing services, results-driven" },
  { id: "marketing-website", name: "Website Marketer", category: "marketing", description: "Marketing services, results-driven" },
  // Medical
  { id: "medical-acupuncture", name: "Acupuncture Clinic", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-chiro", name: "Chiropractic Clinic", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-dentist", name: "Dental Practice", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-derma", name: "Dermatology Clinic", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-doctor", name: "Medical Practice", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-massage", name: "Massage Therapy", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-nutrition", name: "Nutritionist Profile", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-o-t", name: "Occupational Therapy", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-optom", name: "Optometry Practice", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-ortho", name: "Orthopedic Practice", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-p-t", name: "Physical Therapy", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-psych", name: "Psychology Practice", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-psychiatry", name: "Psychiatry Practice", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-specialist", name: "Medical Specialist", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-speech", name: "Speech Therapy", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-telehealth", name: "Telehealth Practice", category: "medical", description: "Medical practice, patient care" },
  { id: "medical-therapy", name: "Therapy Practice", category: "medical", description: "Medical practice, patient care" },
  // Offices
  { id: "office-art", name: "Art Studio", category: "offices", description: "Office space, professional venue" },
  { id: "office-beauty", name: "Beauty Office", category: "offices", description: "Office space, professional venue" },
  { id: "office-conference", name: "Conference Room", category: "offices", description: "Office space, professional venue" },
  { id: "office-cowork", name: "Coworking Space", category: "offices", description: "Office space, professional venue" },
  { id: "office-dance", name: "Dance Studio", category: "offices", description: "Office space, professional venue" },
  { id: "office-event", name: "Event Space", category: "offices", description: "Office space, professional venue" },
  { id: "office-music", name: "Music Studio", category: "offices", description: "Office space, professional venue" },
  { id: "office-photo", name: "Photo Studio", category: "offices", description: "Office space, professional venue" },
  { id: "office-podcast", name: "Podcast Studio", category: "offices", description: "Office space, professional venue" },
  { id: "office-private", name: "Private Office", category: "offices", description: "Office space, professional venue" },
  { id: "office-therapy", name: "Therapy Office", category: "offices", description: "Office space, professional venue" },
  // Pet Services
  { id: "pet-boarding", name: "Pet Boarding", category: "pet-services", description: "Pet services, animal care" },
  { id: "pet-daycare", name: "Pet Daycare", category: "pet-services", description: "Pet services, animal care" },
  { id: "pet-groomer", name: "Pet Groomer", category: "pet-services", description: "Pet services, animal care" },
  { id: "pet-mobile-vet", name: "Mobile Vet", category: "pet-services", description: "Pet services, animal care" },
  { id: "pet-photographer", name: "Pet Photographer", category: "pet-services", description: "Pet services, animal care" },
  { id: "pet-sitter", name: "Pet Sitter", category: "pet-services", description: "Pet services, animal care" },
  { id: "pet-trainer", name: "Pet Trainer", category: "pet-services", description: "Pet services, animal care" },
  { id: "pet-vet", name: "Veterinary Clinic", category: "pet-services", description: "Pet services, animal care" },
  { id: "pet-walker", name: "Dog Walker", category: "pet-services", description: "Pet services, animal care" },
  // Portraits
  { id: "portrait-headshot", name: "Headshot Pro", category: "portraits", description: "Gray, 2-col, pricing packages" },
  { id: "portrait-studio", name: "Studio Light", category: "portraits", description: "White, dramatic shadows, centered" },
  // Real Estate
  { id: "real-estate-agent", name: "Real Estate Agent", category: "real-estate", description: "Real estate, property listings" },
  { id: "real-estate-appraiser", name: "Real Estate Appraiser", category: "real-estate", description: "Real estate, property listings" },
  { id: "real-estate-inspector", name: "Home Inspector", category: "real-estate", description: "Real estate, property listings" },
  { id: "real-estate-investor", name: "Real Estate Investor", category: "real-estate", description: "Real estate, property listings" },
  { id: "real-estate-leasing", name: "Leasing Agent", category: "real-estate", description: "Real estate, property listings" },
  { id: "real-estate-luxury", name: "Luxury Real Estate", category: "real-estate", description: "Real estate, property listings" },
  { id: "real-estate-mortgage", name: "Mortgage Pro", category: "real-estate", description: "Real estate, property listings" },
  { id: "real-estate-property", name: "Property Manager", category: "real-estate", description: "Real estate, property listings" },
  // Restaurant
  { id: "restaurant-bakery", name: "Bakery Shop", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-bar", name: "Bar & Lounge", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-cafe", name: "Cafe Profile", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-casual", name: "Casual Dining", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-catering", name: "Catering Service", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-chef", name: "Private Chef", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-coffee", name: "Coffee Shop", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-dessert", name: "Dessert Shop", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-fine", name: "Fine Dining", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-juice", name: "Juice Bar", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-meal-prep", name: "Meal Prep Service", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-popup", name: "Pop-Up Kitchen", category: "restaurant", description: "Restaurant, menu showcase" },
  { id: "restaurant-truck", name: "Food Truck", category: "restaurant", description: "Restaurant, menu showcase" },
  // Retail
  { id: "retail-book", name: "Bookshop", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-fashion", name: "Fashion Boutique", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-florist", name: "Florist Shop", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-food", name: "Food Shop", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-furniture", name: "Furniture Store", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-gallery", name: "Art Gallery", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-gift", name: "Gift Shop", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-jeweler", name: "Jewelry Store", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-maker", name: "Maker Shop", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-pet", name: "Pet Store", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-toy", name: "Toy Store", category: "retail", description: "Retail shop, product showcase" },
  { id: "retail-vintage", name: "Vintage Shop", category: "retail", description: "Retail shop, product showcase" },
  // Specialty
  { id: "specialty-astrologer", name: "Astrologer Profile", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-genealogist", name: "Genealogist Profile", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-grant", name: "Grant Writer", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-interpreter", name: "Interpreter Services", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-p-i", name: "Private Investigator", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-religious", name: "Religious Leader", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-researcher", name: "Researcher Profile", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-speaker", name: "Keynote Speaker", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-spiritual", name: "Spiritual Guide", category: "specialty", description: "Specialty services, niche expertise" },
  { id: "specialty-translator", name: "Translator Services", category: "specialty", description: "Specialty services, niche expertise" },
  // Sports
  { id: "sports-action", name: "Sports Action", category: "sports", description: "High-energy, dark bg, neon accent" },
  { id: "sports-editorial", name: "Sports Editorial", category: "sports", description: "Magazine-style, white, serif" },
  // Spring
  { id: "spring-blossom", name: "Blossom", category: "spring", description: "Soft pink, rose, delicate" },
  { id: "spring-fresh", name: "Fresh Growth", category: "spring", description: "Light green, emerald, vibrant" },
  // Street
  { id: "street-gritty", name: "Gritty Urban", category: "street", description: "Dark, B&W, film grain" },
  { id: "street-neon", name: "Neon Nights", category: "street", description: "Black, neon cyan/pink, cyberpunk" },
  // Summer
  { id: "summer-beach", name: "Beach Vibes", category: "summer", description: "Sandy, turquoise, waves" },
  { id: "summer-golden", name: "Golden Hour", category: "summer", description: "Sunset gradient, warm glow" },
  // Teaching
  { id: "teaching-acting", name: "Acting Coach", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-admissions", name: "Admissions Consultant", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-art", name: "Art Teacher", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-coding", name: "Coding Instructor", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-course", name: "Course Creator", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-debate", name: "Debate Coach", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-driving", name: "Driving Instructor", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-homeschool", name: "Homeschool Teacher", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-language", name: "Language Tutor", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-music", name: "Music Teacher", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-test-prep", name: "Test Prep Tutor", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-tutor", name: "Private Tutor", category: "teaching", description: "Teaching services, education focus" },
  { id: "teaching-writing", name: "Writing Coach", category: "teaching", description: "Teaching services, education focus" },
  // Tech
  { id: "tech-a-i", name: "AI Specialist", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-app", name: "App Developer", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-automation", name: "Automation Expert", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-cyber", name: "Cybersecurity Pro", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-data", name: "Data Analyst", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-i-t", name: "IT Support", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-no-code", name: "No-Code Developer", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-product", name: "Product Manager", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-software", name: "Software Engineer", category: "tech", description: "Tech services, modern and digital" },
  { id: "tech-support", name: "Tech Support", category: "tech", description: "Tech services, modern and digital" },
  // Travel
  { id: "travel-agent", name: "Travel Agent", category: "travel", description: "Travel services, destination showcase" },
  { id: "travel-airbnb", name: "Airbnb Host", category: "travel", description: "Travel services, destination showcase" },
  { id: "travel-bn-b", name: "Bed & Breakfast", category: "travel", description: "Travel services, destination showcase" },
  { id: "travel-consultant", name: "Travel Consultant", category: "travel", description: "Travel services, destination showcase" },
  { id: "travel-experience", name: "Travel Experience", category: "travel", description: "Travel services, destination showcase" },
  { id: "travel-guide", name: "Tour Guide", category: "travel", description: "Travel services, destination showcase" },
  { id: "travel-hotel", name: "Hotel Profile", category: "travel", description: "Travel services, destination showcase" },
  { id: "travel-retreat", name: "Retreat Host", category: "travel", description: "Travel services, destination showcase" },
  // Winter
  { id: "winter-cozy", name: "Cozy Winter", category: "winter", description: "Warm dark, amber, cabin feel" },
  { id: "winter-frozen", name: "Frozen Elegance", category: "winter", description: "Cool blue, frosted glass" },
];
