import type { TemplateDefinition } from './types.js';

// =============================================================================
// FrameNest v2 — Complete Template Registry (323 templates, 20 industries)
// Each definition is ~12 lines of data. The TemplateRenderer consumes these.
// =============================================================================

export const TEMPLATE_REGISTRY: TemplateDefinition[] = [

  // ═══ PHOTOGRAPHY (34 templates) ═══════════════════════════════════════════
  ...([
    { id: '1-clean', pf: ['photographer'], n: 'Clean', c: { p: '#2563eb', s: '#f8fafc', a: '#f59e0b', b: '#ffffff', t: '#1a1a1a' } },
    { id: '2-cinematic', pf: ['photographer','videographer'], n: 'Cinematic', c: { p: '#0a0a0a', s: '#1a1a1a', a: '#dc2626', b: '#000000', t: '#f5f5f5' } },
    { id: '3-minimal', pf: ['photographer'], n: 'Minimal', c: { p: '#000000', s: '#f5f5f5', a: '#666666', b: '#ffffff', t: '#1a1a1a' } },
    { id: '4-bold', pf: ['photographer'], n: 'Bold', c: { p: '#7c3aed', s: '#ede9fe', a: '#f59e0b', b: '#ffffff', t: '#1a1a1a' } },
    { id: '5-editorial', pf: ['photographer','photojournalist'], n: 'Editorial', c: { p: '#1a1a1a', s: '#f0f0f0', a: '#c4a87c', b: '#fafaf8', t: '#2a2a2a' } },
    { id: '6-nature', pf: ['photographer','landscape-photographer'], n: 'Nature', c: { p: '#2d6a4f', s: '#d8f3dc', a: '#95d5b2', b: '#f7fdf9', t: '#1b4332' } },
    { id: '7-urban', pf: ['photographer','street-photographer'], n: 'Urban', c: { p: '#374151', s: '#e5e7eb', a: '#f97316', b: '#fafafa', t: '#111827' } },
    { id: '8-vintage', pf: ['photographer'], n: 'Vintage', c: { p: '#8b5e3c', s: '#fef3c7', a: '#d4a574', b: '#fffbeb', t: '#3e2723' } },
    { id: '9-moody', pf: ['photographer','portrait-photographer'], n: 'Moody', c: { p: '#1e1e1e', s: '#2d2d2d', a: '#8b7355', b: '#0d0d0d', t: '#d4d4d4' } },
    { id: '10-brutalist', pf: ['photographer'], n: 'Brutalist', c: { p: '#000000', s: '#ffffff', a: '#ff0000', b: '#f0f0f0', t: '#000000' } },
    { id: '11-elegant', pf: ['photographer','wedding-photographer'], n: 'Elegant', c: { p: '#1a1a2e', s: '#f0e6d3', a: '#c9a96e', b: '#faf8f5', t: '#2c2c3e' } },
    { id: '12-pastel', pf: ['photographer','newborn-photographer'], n: 'Pastel', c: { p: '#d4a0c4', s: '#fce4ec', a: '#b8d4e3', b: '#fef9fb', t: '#4a4a4a' } },
    { id: '13-golden', pf: ['photographer','wedding-photographer'], n: 'Golden Hour', c: { p: '#d4a853', s: '#fef3c7', a: '#f59e0b', b: '#fffbeb', t: '#5c3d0e' } },
    { id: '14-ocean', pf: ['photographer','underwater-photographer'], n: 'Ocean', c: { p: '#0077b6', s: '#caf0f8', a: '#00b4d8', b: '#f0f9ff', t: '#03045e' } },
    { id: '15-monochrome', pf: ['photographer','fine-art-photographer'], n: 'Monochrome', c: { p: '#2a2a2a', s: '#e0e0e0', a: '#555555', b: '#ffffff', t: '#1a1a1a' } },
    { id: '16-sunset', pf: ['photographer','landscape-photographer'], n: 'Sunset', c: { p: '#e05a38', s: '#fde2d3', a: '#f4845f', b: '#fef8f5', t: '#4a1a0a' } },
    { id: '17-forest', pf: ['photographer','nature-photographer'], n: 'Forest', c: { p: '#2d6a4f', s: '#d8f0e0', a: '#52b788', b: '#f7fdf9', t: '#0a2a1a' } },
    { id: '18-arctic', pf: ['photographer'], n: 'Arctic', c: { p: '#457b9d', s: '#e0f0f8', a: '#a8dadc', b: '#fafdff', t: '#1d3557' } },
    { id: '19-desert', pf: ['photographer'], n: 'Desert', c: { p: '#c17a3e', s: '#fce4cc', a: '#e6a96c', b: '#fdfaf6', t: '#3e2010' } },
    { id: '20-neon', pf: ['photographer','event-photographer'], n: 'Neon', c: { p: '#ff006e', s: '#1a1a2e', a: '#00f5d4', b: '#0a0a1a', t: '#e0e0e0' } },
    { id: '21-soft', pf: ['photographer','newborn-photographer'], n: 'Soft Touch', c: { p: '#e8b4b8', s: '#fdf2f4', a: '#d4a0a0', b: '#fefbfb', t: '#5c4a4a' } },
    { id: '22-industrial', pf: ['photographer','architectural-photographer'], n: 'Industrial', c: { p: '#4a4a4a', s: '#d4d4d4', a: '#e07a3d', b: '#f5f5f5', t: '#1a1a1a' } },
    { id: '23-botanical', pf: ['photographer','nature-photographer'], n: 'Botanical', c: { p: '#588157', s: '#e9f5e5', a: '#a3b18a', b: '#fafcf9', t: '#344e41' } },
    { id: '24-twilight', pf: ['photographer','night-photographer'], n: 'Twilight', c: { p: '#3a0ca3', s: '#e0d4f5', a: '#7209b7', b: '#f8f5fd', t: '#1a0533' } },
    { id: '25-coastal', pf: ['photographer'], n: 'Coastal', c: { p: '#219ebc', s: '#e0f4f8', a: '#ffb703', b: '#fafefe', t: '#023047' } },
    { id: '26-autumn', pf: ['photographer'], n: 'Autumn', c: { p: '#bc6c25', s: '#fef0d5', a: '#dda15e', b: '#fdf8f2', t: '#582f0e' } },
    { id: '27-spring', pf: ['photographer'], n: 'Spring', c: { p: '#95d5b2', s: '#e8f5ec', a: '#d4a0c4', b: '#fafdfb', t: '#2d5a3f' } },
    { id: '28-winter', pf: ['photographer'], n: 'Winter', c: { p: '#6c7a89', s: '#e8ecf0', a: '#a0b4c8', b: '#fafbfc', t: '#2c3e50' } },
    { id: '29-summer', pf: ['photographer'], n: 'Summer', c: { p: '#f4a261', s: '#fef3e4', a: '#e76f51', b: '#fefaf6', t: '#4a2a10' } },
    { id: '30-aerial', pf: ['photographer','drone-photographer'], n: 'Aerial', c: { p: '#2a9d8f', s: '#e0f5f2', a: '#e9c46a', b: '#f8fdfc', t: '#264653' } },
    { id: '31-studio', pf: ['photographer','studio-photographer'], n: 'Studio', c: { p: '#333333', s: '#e8e8e8', a: '#cccccc', b: '#fafafa', t: '#111111' } },
    { id: '32-documentary', pf: ['photographer','documentary-photographer'], n: 'Documentary', c: { p: '#2a2a2a', s: '#f0ede4', a: '#8b6f4e', b: '#faf8f3', t: '#1a1a1a' } },
    { id: '33-fine-art', pf: ['photographer','fine-art-photographer'], n: 'Fine Art', c: { p: '#4a4a4a', s: '#f5f0eb', a: '#b8a99a', b: '#fdfcfb', t: '#2a2a2a' } },
    { id: '34-sports', pf: ['photographer','sports-photographer'], n: 'Sports', c: { p: '#e63946', s: '#f1f1f1', a: '#1d3557', b: '#ffffff', t: '#1a1a2e' } },
  ] as Array<{ id: string; pf: string[]; n: string; c: ShorthandColors }>).map(t => tpl(t.id, 'photography', t.pf, t.n, t.c)),

  // ═══ TEACHING (13 templates) ═══════════════════════════════════════════════
  ...([
    { id: 'teaching-music', pf: ['music-teacher','piano-teacher'], n: 'Music Studio', c: { p: '#5c4d7d', s: '#f0edf5', a: '#d4a853', b: '#faf9fc', t: '#2a2040' } },
    { id: 'teaching-math', pf: ['math-tutor','tutor'], n: 'Math Mastery', c: { p: '#247ba0', s: '#e0f0f7', a: '#f4a261', b: '#f8fbfd', t: '#1a3a4a' } },
    { id: 'teaching-language', pf: ['language-tutor','esl-teacher'], n: 'Language Lab', c: { p: '#2a9d8f', s: '#e6f5f3', a: '#e9c46a', b: '#f9fdfc', t: '#1a3a35' } },
    { id: 'teaching-art', pf: ['art-teacher'], n: 'Art Studio', c: { p: '#e76f51', s: '#fef0eb', a: '#2a9d8f', b: '#fdfaf8', t: '#3e1510' } },
    { id: 'teaching-science', pf: ['science-tutor','stem-tutor'], n: 'Science Lab', c: { p: '#1d4e89', s: '#e0eaf5', a: '#4ea8de', b: '#f7fafd', t: '#0a1a3a' } },
    { id: 'teaching-dance', pf: ['dance-instructor','ballet-teacher'], n: 'Dance Academy', c: { p: '#d4a0c4', s: '#fdf2f8', a: '#e8b4b8', b: '#fefbfd', t: '#4a2a4a' } },
    { id: 'teaching-yoga', pf: ['yoga-instructor'], n: 'Yoga Studio', c: { p: '#6b8f71', s: '#eaf2eb', a: '#c4a87c', b: '#f9fbf9', t: '#2a3a2a' } },
    { id: 'teaching-coding', pf: ['coding-tutor','tech-instructor'], n: 'Code Camp', c: { p: '#2d2d44', s: '#e8e8f0', a: '#00d4aa', b: '#f5f5fa', t: '#1a1a2e' } },
    { id: 'teaching-driving', pf: ['driving-instructor'], n: 'Drive School', c: { p: '#e63946', s: '#fef0f0', a: '#457b9d', b: '#fdfafa', t: '#2a0a0a' } },
    { id: 'teaching-cooking', pf: ['cooking-instructor','chef-instructor'], n: 'Cooking School', c: { p: '#d4773a', s: '#fef3e8', a: '#8b5e3c', b: '#fdfaf7', t: '#3e1a0a' } },
    { id: 'teaching-academic', pf: ['academic-tutor','college-counselor'], n: 'Academic Prep', c: { p: '#1d3557', s: '#e8edf5', a: '#a8dadc', b: '#f8fafd', t: '#0a1a2e' } },
    { id: 'teaching-martial', pf: ['martial-arts-instructor'], n: 'Martial Arts', c: { p: '#1a1a1a', s: '#f0f0f0', a: '#dc2626', b: '#fafafa', t: '#0a0a0a' } },
    { id: 'teaching-special-ed', pf: ['special-ed-teacher'], n: 'Special Education', c: { p: '#7c8cc4', s: '#f0f2fa', a: '#f4d35e', b: '#fafbfd', t: '#2a2a4a' } },
  ] as Array<{ id: string; pf: string[]; n: string; c: ShorthandColors }>).map(t => tpl(t.id, 'teaching', t.pf, t.n, t.c)),

  // ═══ COACHING (10 templates) ═══════════════════════════════════════════════
  ...([
    { id: 'coaching-life', pf: ['life-coach'], n: 'Life Coach', c: { p: '#5b8c5a', s: '#edf5ed', a: '#d4a853', b: '#f9fcf9', t: '#2a3a2a' } },
    { id: 'coaching-business', pf: ['business-coach','executive-coach'], n: 'Business Coach', c: { p: '#1d3557', s: '#e8edf5', a: '#e6b84c', b: '#f7fafd', t: '#0a1a2e' } },
    { id: 'coaching-fitness', pf: ['fitness-coach','personal-trainer'], n: 'Fitness Coach', c: { p: '#e63946', s: '#fef0f0', a: '#2d2d2d', b: '#fdfafa', t: '#2a0a0a' } },
    { id: 'coaching-career', pf: ['career-coach'], n: 'Career Coach', c: { p: '#457b9d', s: '#e6f0f7', a: '#f4a261', b: '#f8fbfd', t: '#1a2a3a' } },
    { id: 'coaching-health', pf: ['health-coach','wellness-coach'], n: 'Health Coach', c: { p: '#6b8f71', s: '#edf5ef', a: '#d4a0c4', b: '#f9fcf9', t: '#2a3a2a' } },
    { id: 'coaching-adhd', pf: ['adhd-coach'], n: 'ADHD Coach', c: { p: '#7c3aed', s: '#f3edfd', a: '#f59e0b', b: '#faf9fe', t: '#2a0a5e' } },
    { id: 'coaching-relationship', pf: ['relationship-coach'], n: 'Relationship Coach', c: { p: '#d4a0c4', s: '#fdf2f8', a: '#e8b4b8', b: '#fefbfd', t: '#4a2a3a' } },
    { id: 'coaching-financial', pf: ['financial-coach'], n: 'Financial Coach', c: { p: '#2d6a4f', s: '#e8f5ed', a: '#d4a853', b: '#f7fdf9', t: '#0a2a1a' } },
    { id: 'coaching-public-speaking', pf: ['public-speaking-coach'], n: 'Public Speaking', c: { p: '#1d3557', s: '#eeeeff', a: '#e63946', b: '#fafafe', t: '#0a0a2e' } },
    { id: 'coaching-sleep', pf: ['sleep-coach'], n: 'Sleep Coach', c: { p: '#3a3a6e', s: '#ededf8', a: '#a0b4c8', b: '#f8f8fd', t: '#1a1a3e' } },
  ] as Array<{ id: string; pf: string[]; n: string; c: ShorthandColors }>).map(t => tpl(t.id, 'coaching', t.pf, t.n, t.c)),

  // ═══ MEDICAL (17) ═════════════════════════════════════════════════════════
  ...([{id:'medical-dentistry',pf:['dentist','orthodontist','oral-surgeon'],n:'Dental Practice',c:{p:'#006D77',s:'#E0F0F0',a:'#FFDDD2',b:'#FFFFFF',t:'#1A1A1A'}},{id:'medical-general',pf:['general-practitioner','family-doctor'],n:'Family Medicine',c:{p:'#1B6B93',s:'#E6F0F7',a:'#4FC3F7',b:'#F7FBFD',t:'#0A2A3A'}},{id:'medical-dermatology',pf:['dermatologist'],n:'Dermatology',c:{p:'#7B4B94',s:'#F3EDF7',a:'#D4A0C4',b:'#FDFBFE',t:'#3A1A4A'}},{id:'medical-pediatric',pf:['pediatrician'],n:'Pediatrics',c:{p:'#FF6B6B',s:'#FFF0F0',a:'#FFD93D',b:'#FFFBFB',t:'#4A0A0A'}},{id:'medical-ophthalmology',pf:['ophthalmologist','optometrist'],n:'Eye Care',c:{p:'#0D47A1',s:'#E3F2FD',a:'#42A5F5',b:'#F8FBFE',t:'#0A1A3A'}},{id:'medical-cardiology',pf:['cardiologist'],n:'Heart Center',c:{p:'#C62828',s:'#FFEBEE',a:'#EF5350',b:'#FFF8F8',t:'#3A0A0A'}},{id:'medical-orthopedic',pf:['orthopedic-surgeon'],n:'Orthopedics',c:{p:'#37474F',s:'#ECEFF1',a:'#FF7043',b:'#FAFAFA',t:'#1A1A1A'}},{id:'medical-neurology',pf:['neurologist'],n:'Neurology',c:{p:'#4A148C',s:'#F3E5F5',a:'#AB47BC',b:'#FDF8FE',t:'#1A0A3A'}},{id:'medical-physical-therapy',pf:['physical-therapist'],n:'Physical Therapy',c:{p:'#2E7D32',s:'#E8F5E9',a:'#66BB6A',b:'#F7FDF7',t:'#0A2A0A'}},{id:'medical-chiropractic',pf:['chiropractor'],n:'Chiropractic',c:{p:'#5D4037',s:'#EFEBE9',a:'#8D6E63',b:'#FAF8F7',t:'#2A1A0A'}},{id:'medical-acupuncture',pf:['acupuncturist'],n:'Acupuncture',c:{p:'#00695C',s:'#E0F2F1',a:'#4DB6AC',b:'#F7FDFC',t:'#0A2A20'}},{id:'medical-psychiatry',pf:['psychiatrist','therapist'],n:'Psychiatry',c:{p:'#4527A0',s:'#EDE7F6',a:'#7986CB',b:'#F9F8FD',t:'#1A0A3A'}},{id:'medical-obgyn',pf:['obgyn'],n:'OB/GYN',c:{p:'#C2185B',s:'#FCE4EC',a:'#F48FB1',b:'#FEFAFC',t:'#3A0A2A'}},{id:'medical-allergy',pf:['allergist'],n:'Allergy Care',c:{p:'#00838F',s:'#E0F7FA',a:'#4DD0E1',b:'#F7FDFE',t:'#0A2A3A'}},{id:'medical-ent',pf:['ent-specialist'],n:'ENT Specialist',c:{p:'#1565C0',s:'#E3F2FD',a:'#64B5F6',b:'#F8FBFE',t:'#0A1A3A'}},{id:'medical-oncology',pf:['oncologist'],n:'Oncology',c:{p:'#6A1B9A',s:'#F3E5F5',a:'#BA68C8',b:'#FDFAFE',t:'#2A0A4A'}},{id:'medical-urgent',pf:['urgent-care'],n:'Urgent Care',c:{p:'#D84315',s:'#FBE9E7',a:'#FF8A65',b:'#FFF8F6',t:'#3A1000'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'medical',t.pf,t.n,t.c)),

  // ═══ LEGAL (14) ═══════════════════════════════════════════════════════════
  ...([{id:'legal-family',pf:['family-lawyer','divorce-attorney'],n:'Family Law',c:{p:'#283593',s:'#E8EAF6',a:'#7986CB',b:'#F8F9FD',t:'#0A0A2A'}},{id:'legal-criminal',pf:['criminal-defense'],n:'Criminal Defense',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#9E9E9E',b:'#FAFAFA',t:'#0A0A0A'}},{id:'legal-corporate',pf:['corporate-lawyer'],n:'Corporate Law',c:{p:'#0D47A1',s:'#E3F2FD',a:'#BBDEFB',b:'#F8FBFE',t:'#0A1A2A'}},{id:'legal-immigration',pf:['immigration-lawyer'],n:'Immigration Law',c:{p:'#00695C',s:'#E0F2F1',a:'#80CBC4',b:'#F7FDFC',t:'#0A2A20'}},{id:'legal-estate',pf:['estate-planner'],n:'Estate Planning',c:{p:'#5D4037',s:'#EFEBE9',a:'#BCAAA4',b:'#FAF8F7',t:'#2A1A0A'}},{id:'legal-personal-injury',pf:['personal-injury-lawyer'],n:'Personal Injury',c:{p:'#B71C1C',s:'#FFEBEE',a:'#EF9A9A',b:'#FFF8F8',t:'#3A0A0A'}},{id:'legal-cpa',pf:['cpa','accountant'],n:'CPA Firm',c:{p:'#1B5E20',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'legal-tax',pf:['tax-attorney'],n:'Tax Law',c:{p:'#33691E',s:'#F1F8E9',a:'#AED581',b:'#F9FDF8',t:'#1A2A0A'}},{id:'legal-employment',pf:['employment-lawyer'],n:'Employment Law',c:{p:'#E65100',s:'#FFF3E0',a:'#FFB74D',b:'#FFFBF7',t:'#3A1A00'}},{id:'legal-ip',pf:['ip-lawyer','patent-attorney'],n:'IP Law',c:{p:'#4A148C',s:'#F3E5F5',a:'#CE93D8',b:'#FDF8FE',t:'#1A0A3A'}},{id:'legal-hr',pf:['hr-consultant'],n:'HR Consulting',c:{p:'#0277BD',s:'#E1F5FE',a:'#4FC3F7',b:'#F7FDFF',t:'#0A1A2A'}},{id:'legal-bankruptcy',pf:['bankruptcy-lawyer'],n:'Bankruptcy Law',c:{p:'#37474F',s:'#ECEFF1',a:'#90A4AE',b:'#FAFAFA',t:'#1A1A1A'}},{id:'legal-real-estate',pf:['real-estate-lawyer'],n:'Real Estate Law',c:{p:'#3E2723',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#1A0A00'}},{id:'legal-consulting',pf:['legal-consultant'],n:'Legal Consulting',c:{p:'#1A237E',s:'#E8EAF6',a:'#9FA8DA',b:'#F8F9FD',t:'#0A0A3A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'legal',t.pf,t.n,t.c)),

  // ═══ BEAUTY (12) ═════════════════════════════════════════════════════════
  ...([{id:'beauty-salon',pf:['hair-stylist','salon-owner'],n:'Hair Salon',c:{p:'#AD1457',s:'#FCE4EC',a:'#F48FB1',b:'#FEFAFC',t:'#3A0A2A'}},{id:'beauty-spa',pf:['spa-owner','massage-therapist'],n:'Day Spa',c:{p:'#6A8D73',s:'#EDF5EF',a:'#C4A87C',b:'#F9FCF9',t:'#2A3A2A'}},{id:'beauty-nails',pf:['nail-technician'],n:'Nail Studio',c:{p:'#D81B60',s:'#FCE4EC',a:'#F06292',b:'#FDFAFC',t:'#4A0A2A'}},{id:'beauty-makeup',pf:['makeup-artist'],n:'Makeup Artist',c:{p:'#8E24AA',s:'#F3E5F5',a:'#BA68C8',b:'#FDF8FE',t:'#2A0A3A'}},{id:'beauty-barber',pf:['barber'],n:'Barbershop',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#8D6E63',b:'#FAFAFA',t:'#0A0A0A'}},{id:'beauty-lashes',pf:['lash-technician'],n:'Lash Studio',c:{p:'#C2185B',s:'#FCE4EC',a:'#F8BBD0',b:'#FEFAFC',t:'#3A0A2A'}},{id:'beauty-skincare',pf:['esthetician'],n:'Skincare Clinic',c:{p:'#00897B',s:'#E0F2F1',a:'#80CBC4',b:'#F7FDFC',t:'#0A2A20'}},{id:'beauty-tattoo',pf:['tattoo-artist'],n:'Tattoo Studio',c:{p:'#1A1A1A',s:'#E8E8E8',a:'#D32F2F',b:'#F8F8F8',t:'#0A0A0A'}},{id:'beauty-waxing',pf:['waxing-specialist'],n:'Waxing Studio',c:{p:'#E91E63',s:'#FCE4EC',a:'#EC407A',b:'#FEFAFC',t:'#3A0A1A'}},{id:'beauty-brows',pf:['brow-artist','microblading'],n:'Brow Studio',c:{p:'#6D4C41',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#2A1A0A'}},{id:'beauty-bridal',pf:['bridal-stylist'],n:'Bridal Beauty',c:{p:'#D4A0C4',s:'#FDF2F8',a:'#E8B4B8',b:'#FEFBFD',t:'#4A2A3A'}},{id:'beauty-barber-college',pf:['barber-college'],n:'Barber College',c:{p:'#37474F',s:'#ECEFF1',a:'#B0BEC5',b:'#FAFAFA',t:'#1A1A1A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'beauty',t.pf,t.n,t.c)),

  // ═══ FITNESS (8) ══════════════════════════════════════════════════════════
  ...([{id:'fitness-gym',pf:['gym-owner','personal-trainer'],n:'Gym',c:{p:'#424242',s:'#EEEEEE',a:'#FF5722',b:'#FAFAFA',t:'#1A1A1A'}},{id:'fitness-yoga',pf:['yoga-studio'],n:'Yoga Studio',c:{p:'#6B8F71',s:'#EAF2EB',a:'#C4A87C',b:'#F9FBF9',t:'#2A3A2A'}},{id:'fitness-pilates',pf:['pilates-studio'],n:'Pilates Studio',c:{p:'#5C6BC0',s:'#E8EAF6',a:'#9FA8DA',b:'#F8F9FD',t:'#1A1A3A'}},{id:'fitness-crossfit',pf:['crossfit-box'],n:'CrossFit Box',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#F44336',b:'#F8F8F8',t:'#0A0A0A'}},{id:'fitness-cycling',pf:[' cycling-studio'],n:'Cycling Studio',c:{p:'#E53935',s:'#FFEBEE',a:'#1A1A1A',b:'#FDF8F8',t:'#2A0A0A'}},{id:'fitness-martial',pf:['martial-arts-gym'],n:'Martial Arts Gym',c:{p:'#1A1A1A',s:'#EEEEEE',a:'#D32F2F',b:'#F8F8F8',t:'#0A0A0A'}},{id:'fitness-swim',pf:['swim-school'],n:'Swim School',c:{p:'#0277BD',s:'#E1F5FE',a:'#4FC3F7',b:'#F7FDFF',t:'#0A1A2A'}},{id:'fitness-dance',pf:['dance-studio'],n:'Dance Studio',c:{p:'#7B1FA2',s:'#F3E5F5',a:'#BA68C8',b:'#FDF8FE',t:'#2A0A4A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'fitness',t.pf,t.n,t.c)),

  // ═══ CREATIVE (14) ════════════════════════════════════════════════════════
  ...([{id:'creative-designer',pf:['graphic-designer'],n:'Graphic Design',c:{p:'#FF5722',s:'#FBE9E7',a:'#FF8A65',b:'#FDF9F8',t:'#2A1000'}},{id:'creative-illustrator',pf:['illustrator'],n:'Illustration',c:{p:'#5C6BC0',s:'#E8EAF6',a:'#9FA8DA',b:'#F8F9FD',t:'#1A1A3A'}},{id:'creative-animator',pf:['animator','motion-designer'],n:'Animation',c:{p:'#4527A0',s:'#EDE7F6',a:'#B39DDB',b:'#F9F8FD',t:'#1A0A3A'}},{id:'creative-writer',pf:['writer','copywriter'],n:'Writer',c:{p:'#2A2A2A',s:'#F5F0EB',a:'#8B6F4E',b:'#FAF8F5',t:'#1A1A1A'}},{id:'creative-architect',pf:['architect'],n:'Architecture',c:{p:'#37474F',s:'#ECEFF1',a:'#78909C',b:'#FAFAFA',t:'#1A1A1A'}},{id:'creative-interior',pf:['interior-designer'],n:'Interior Design',c:{p:'#8D6E63',s:'#EFEBE9',a:'#BCAAA4',b:'#FAF8F7',t:'#2A1A0A'}},{id:'creative-florist',pf:['florist'],n:'Florist',c:{p:'#E91E63',s:'#FCE4EC',a:'#F48FB1',b:'#FEFAFC',t:'#3A0A2A'}},{id:'creative-musician',pf:['musician','music-producer'],n:'Musician',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#FFD700',b:'#FAFAFA',t:'#0A0A0A'}},{id:'creative-filmmaker',pf:['filmmaker','video-producer'],n:'Filmmaker',c:{p:'#0A0A0A',s:'#1A1A1A',a:'#DC2626',b:'#000000',t:'#F0F0F0'}},{id:'creative-painter',pf:['painter','fine-artist'],n:'Painter',c:{p:'#D84315',s:'#FBE9E7',a:'#FF8A65',b:'#FDF8F6',t:'#2A1000'}},{id:'creative-web',pf:['web-designer','ux-designer'],n:'Web Design',c:{p:'#1565C0',s:'#E3F2FD',a:'#64B5F6',b:'#F8FBFE',t:'#0A1A3A'}},{id:'creative-craft',pf:['craft-artist','maker'],n:'Craft Studio',c:{p:'#6D4C41',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#2A1A0A'}},{id:'creative-pottery',pf:['potter','ceramicist'],n:'Pottery Studio',c:{p:'#8D6E63',s:'#EFEBE9',a:'#D7CCC8',b:'#FAF8F7',t:'#2A1A00'}},{id:'creative-jewelry',pf:['jewelry-designer'],n:'Jewelry Design',c:{p:'#FF8F00',s:'#FFF8E1',a:'#FFD54F',b:'#FFFEFA',t:'#3A2000'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'creative',t.pf,t.n,t.c)),

  // ═══ MARKETING (11) ═══════════════════════════════════════════════════════
  ...([{id:'marketing-agency',pf:['marketing-agency'],n:'Marketing Agency',c:{p:'#1565C0',s:'#E3F2FD',a:'#FF8F00',b:'#F8FBFE',t:'#0A1A2A'}},{id:'marketing-seo',pf:['seo-consultant'],n:'SEO Consultant',c:{p:'#2E7D32',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'marketing-social',pf:['social-media-manager'],n:'Social Media',c:{p:'#E91E63',s:'#FCE4EC',a:'#FF8A65',b:'#FEFAFC',t:'#2A0A1A'}},{id:'marketing-content',pf:['content-marketer'],n:'Content Marketing',c:{p:'#4527A0',s:'#EDE7F6',a:'#FF7043',b:'#F9F8FD',t:'#1A0A3A'}},{id:'marketing-email',pf:['email-marketer'],n:'Email Marketing',c:{p:'#00838F',s:'#E0F7FA',a:'#4DD0E1',b:'#F7FDFE',t:'#0A2A3A'}},{id:'marketing-ppc',pf:['ppc-specialist'],n:'PPC Management',c:{p:'#33691E',s:'#F1F8E9',a:'#FFB300',b:'#F9FDF8',t:'#1A2A00'}},{id:'marketing-brand',pf:['brand-strategist'],n:'Brand Strategy',c:{p:'#1A1A1A',s:'#F5F5F5',a:'#FF5722',b:'#FAFAFA',t:'#0A0A0A'}},{id:'marketing-pr',pf:['pr-consultant'],n:'PR Agency',c:{p:'#0D47A1',s:'#E3F2FD',a:'#BBDEFB',b:'#F8FBFE',t:'#0A1A2A'}},{id:'marketing-analytics',pf:['marketing-analyst'],n:'Marketing Analytics',c:{p:'#37474F',s:'#ECEFF1',a:'#26C6DA',b:'#FAFAFA',t:'#1A1A1A'}},{id:'marketing-video',pf:['video-marketer'],n:'Video Marketing',c:{p:'#D84315',s:'#FBE9E7',a:'#FF8A65',b:'#FDF8F6',t:'#2A1000'}},{id:'marketing-growth',pf:['growth-hacker'],n:'Growth Agency',c:{p:'#6A1B9A',s:'#F3E5F5',a:'#FF4081',b:'#FDFAFE',t:'#2A0A4A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'marketing',t.pf,t.n,t.c)),

  // ═══ REMAINING INDUSTRIES — grouped together ═════════════════════════════

  // INFLUENCER (12)
  ...([{id:'influencer-lifestyle',pf:['lifestyle-influencer'],n:'Lifestyle',c:{p:'#E91E63',s:'#FCE4EC',a:'#F48FB1',b:'#FEFAFC',t:'#2A0A1A'}},{id:'influencer-fashion',pf:['fashion-influencer'],n:'Fashion',c:{p:'#1A1A1A',s:'#F5F5F5',a:'#D4AF37',b:'#FAFAFA',t:'#0A0A0A'}},{id:'influencer-food',pf:['food-blogger'],n:'Food Blog',c:{p:'#D84315',s:'#FBE9E7',a:'#FF8A65',b:'#FDF8F6',t:'#2A1000'}},{id:'influencer-travel',pf:['travel-influencer'],n:'Travel Blog',c:{p:'#0277BD',s:'#E1F5FE',a:'#4FC3F7',b:'#F7FDFF',t:'#0A1A2A'}},{id:'influencer-fitness',pf:['fitness-influencer'],n:'Fitness Influencer',c:{p:'#E53935',s:'#FFEBEE',a:'#1A1A1A',b:'#FDF8F8',t:'#2A0A0A'}},{id:'influencer-beauty',pf:['beauty-influencer'],n:'Beauty Blog',c:{p:'#AD1457',s:'#FCE4EC',a:'#F48FB1',b:'#FEFAFC',t:'#3A0A2A'}},{id:'influencer-tech',pf:['tech-reviewer'],n:'Tech Review',c:{p:'#1A1A1A',s:'#E8E8E8',a:'#00E676',b:'#F8F8F8',t:'#0A0A0A'}},{id:'influencer-gaming',pf:['gaming-influencer'],n:'Gaming',c:{p:'#311B92',s:'#EDE7F6',a:'#7C4DFF',b:'#0A0A1A',t:'#E0E0E0'}},{id:'influencer-parenting',pf:['parenting-blogger'],n:'Parenting Blog',c:{p:'#6B8F71',s:'#EAF2EB',a:'#C4A87C',b:'#F9FBF9',t:'#2A3A2A'}},{id:'influencer-diy',pf:['diy-influencer'],n:'DIY Creator',c:{p:'#FF8F00',s:'#FFF8E1',a:'#FFB300',b:'#FFFEFA',t:'#3A2000'}},{id:'influencer-pet',pf:['pet-influencer'],n:'Pet Blog',c:{p:'#5D4037',s:'#EFEBE9',a:'#FF7043',b:'#FAF8F7',t:'#2A1A0A'}},{id:'influencer-education',pf:['edu-influencer'],n:'Education Blog',c:{p:'#1565C0',s:'#E3F2FD',a:'#42A5F5',b:'#F8FBFE',t:'#0A1A3A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'influencer',t.pf,t.n,t.c)),

  // REAL ESTATE (8)
  ...([{id:'realestate-agent',pf:['real-estate-agent'],n:'Real Estate Agent',c:{p:'#1B5E20',s:'#E8F5E9',a:'#FF8F00',b:'#F7FDF7',t:'#0A2A0A'}},{id:'realestate-broker',pf:['real-estate-broker'],n:'Brokerage',c:{p:'#0D47A1',s:'#E3F2FD',a:'#FFB300',b:'#F8FBFE',t:'#0A1A2A'}},{id:'realestate-luxury',pf:['luxury-agent'],n:'Luxury Real Estate',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#D4AF37',b:'#FAFAFA',t:'#0A0A0A'}},{id:'realestate-commercial',pf:['commercial-agent'],n:'Commercial',c:{p:'#37474F',s:'#ECEFF1',a:'#26C6DA',b:'#FAFAFA',t:'#1A1A1A'}},{id:'realestate-property-mgr',pf:['property-manager'],n:'Property Management',c:{p:'#6D4C41',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#2A1A0A'}},{id:'realestate-stager',pf:['home-stager'],n:'Home Staging',c:{p:'#8D6E63',s:'#EFEBE9',a:'#BCAAA4',b:'#FAF8F7',t:'#2A1A0A'}},{id:'realestate-inspector',pf:['home-inspector'],n:'Home Inspection',c:{p:'#5D4037',s:'#EFEBE9',a:'#8D6E63',b:'#FAF8F7',t:'#2A1A0A'}},{id:'realestate-appraiser',pf:['appraiser'],n:'Appraisal',c:{p:'#455A64',s:'#ECEFF1',a:'#90A4AE',b:'#FAFAFA',t:'#1A1A1A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'real-estate',t.pf,t.n,t.c)),

  // HOME SERVICES (15)
  ...([{id:'home-plumbing',pf:['plumber'],n:'Plumbing',c:{p:'#0277BD',s:'#E1F5FE',a:'#4FC3F7',b:'#F7FDFF',t:'#0A1A2A'}},{id:'home-electrical',pf:['electrician'],n:'Electrical',c:{p:'#FF8F00',s:'#FFF8E1',a:'#FFB300',b:'#FFFEFA',t:'#3A2000'}},{id:'home-hvac',pf:['hvac-technician'],n:'HVAC',c:{p:'#D84315',s:'#FBE9E7',a:'#FF8A65',b:'#FDF8F6',t:'#2A1000'}},{id:'home-roofing',pf:['roofer'],n:'Roofing',c:{p:'#4E342E',s:'#EFEBE9',a:'#8D6E63',b:'#FAF8F7',t:'#2A1A0A'}},{id:'home-landscaping',pf:['landscaper'],n:'Landscaping',c:{p:'#2E7D32',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'home-painting',pf:['painter-contractor'],n:'Painting',c:{p:'#E91E63',s:'#FCE4EC',a:'#F48FB1',b:'#FEFAFC',t:'#2A0A1A'}},{id:'home-cleaning',pf:['cleaning-service'],n:'Cleaning',c:{p:'#00897B',s:'#E0F2F1',a:'#80CBC4',b:'#F7FDFC',t:'#0A2A20'}},{id:'home-moving',pf:['moving-company'],n:'Moving',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#FF5722',b:'#FAFAFA',t:'#0A0A0A'}},{id:'home-pest',pf:['pest-control'],n:'Pest Control',c:{p:'#33691E',s:'#F1F8E9',a:'#8BC34A',b:'#F9FDF8',t:'#1A2A0A'}},{id:'home-remodeling',pf:['remodeler'],n:'Remodeling',c:{p:'#5D4037',s:'#EFEBE9',a:'#FF7043',b:'#FAF8F7',t:'#2A1A0A'}},{id:'home-garage',pf:['garage-door-installer'],n:'Garage Doors',c:{p:'#455A64',s:'#ECEFF1',a:'#90A4AE',b:'#FAFAFA',t:'#1A1A1A'}},{id:'home-locksmith',pf:['locksmith'],n:'Locksmith',c:{p:'#37474F',s:'#ECEFF1',a:'#FFB300',b:'#FAFAFA',t:'#1A1A1A'}},{id:'home-carpet',pf:['carpet-cleaner'],n:'Carpet Cleaning',c:{p:'#6A1B9A',s:'#F3E5F5',a:'#BA68C8',b:'#FDFAFE',t:'#2A0A4A'}},{id:'home-window',pf:['window-cleaner'],n:'Window Cleaning',c:{p:'#0277BD',s:'#E1F5FE',a:'#81D4FA',b:'#F7FDFF',t:'#0A1A2A'}},{id:'home-handyman',pf:['handyman'],n:'Handyman',c:{p:'#6D4C41',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#2A1A0A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'home-services',t.pf,t.n,t.c)),

  // RESTAURANT (13)
  ...([{id:'restaurant-fine',pf:['fine-dining'],n:'Fine Dining',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#D4AF37',b:'#FAFAFA',t:'#0A0A0A'}},{id:'restaurant-casual',pf:['casual-dining'],n:'Casual Dining',c:{p:'#E65100',s:'#FFF3E0',a:'#FFB74D',b:'#FFFBF7',t:'#3A1A00'}},{id:'restaurant-cafe',pf:['cafe','coffee-shop'],n:'Cafe',c:{p:'#6D4C41',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#2A1A0A'}},{id:'restaurant-pizza',pf:['pizzeria'],n:'Pizzeria',c:{p:'#C62828',s:'#FFEBEE',a:'#EF5350',b:'#FFF8F8',t:'#3A0A0A'}},{id:'restaurant-sushi',pf:['sushi-restaurant'],n:'Sushi Bar',c:{p:'#1A1A1A',s:'#F5F5F5',a:'#F44336',b:'#FAFAFA',t:'#0A0A0A'}},{id:'restaurant-bakery',pf:['bakery'],n:'Bakery',c:{p:'#8D6E63',s:'#EFEBE9',a:'#FFAB40',b:'#FAF8F7',t:'#2A1A0A'}},{id:'restaurant-bbq',pf:['bbq-restaurant'],n:'BBQ Joint',c:{p:'#D84315',s:'#FBE9E7',a:'#FF8A65',b:'#FDF8F6',t:'#2A1000'}},{id:'restaurant-vegan',pf:['vegan-restaurant'],n:'Vegan Kitchen',c:{p:'#2E7D32',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'restaurant-foodtruck',pf:['food-truck'],n:'Food Truck',c:{p:'#FF6F00',s:'#FFF3E0',a:'#FFB74D',b:'#FFFBF7',t:'#3A1A00'}},{id:'restaurant-seafood',pf:['seafood-restaurant'],n:'Seafood',c:{p:'#0277BD',s:'#E1F5FE',a:'#4FC3F7',b:'#F7FDFF',t:'#0A1A2A'}},{id:'restaurant-italian',pf:['italian-restaurant'],n:'Italian',c:{p:'#B71C1C',s:'#FFEBEE',a:'#2E7D32',b:'#FDF8F8',t:'#3A0A0A'}},{id:'restaurant-brewery',pf:['brewery','taproom'],n:'Brewery',c:{p:'#3E2723',s:'#EFEBE9',a:'#FF8F00',b:'#F8F6F5',t:'#1A0A00'}},{id:'restaurant-catering',pf:['catering'],n:'Catering',c:{p:'#5D4037',s:'#EFEBE9',a:'#D4A853',b:'#FAF8F7',t:'#2A1A0A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'restaurant',t.pf,t.n,t.c)),

  // RETAIL (12)
  ...([{id:'retail-boutique',pf:['boutique-owner'],n:'Boutique',c:{p:'#C2185B',s:'#FCE4EC',a:'#F48FB1',b:'#FEFAFC',t:'#3A0A2A'}},{id:'retail-florist',pf:['florist-shop'],n:'Flower Shop',c:{p:'#E91E63',s:'#FCE4EC',a:'#81C784',b:'#FDFAFC',t:'#2A0A1A'}},{id:'retail-bookstore',pf:['bookstore'],n:'Bookstore',c:{p:'#5D4037',s:'#EFEBE9',a:'#8D6E63',b:'#F8F6F5',t:'#2A1A0A'}},{id:'retail-vintage',pf:['vintage-shop'],n:'Vintage Shop',c:{p:'#8D6E63',s:'#EFEBE9',a:'#D4A853',b:'#FAF8F7',t:'#2A1A0A'}},{id:'retail-jewelry',pf:['jewelry-store'],n:'Jewelry Store',c:{p:'#1A1A1A',s:'#F5F5F5',a:'#D4AF37',b:'#FAFAFA',t:'#0A0A0A'}},{id:'retail-organic',pf:['organic-market'],n:'Organic Market',c:{p:'#2E7D32',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'retail-electronics',pf:['electronics-store'],n:'Electronics',c:{p:'#1565C0',s:'#E3F2FD',a:'#42A5F5',b:'#F8FBFE',t:'#0A1A3A'}},{id:'retail-furniture',pf:['furniture-store'],n:'Furniture',c:{p:'#6D4C41',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#2A1A0A'}},{id:'retail-bike',pf:['bike-shop'],n:'Bike Shop',c:{p:'#E65100',s:'#FFF3E0',a:'#FFB74D',b:'#FFFBF7',t:'#3A1A00'}},{id:'retail-pet',pf:['pet-store'],n:'Pet Store',c:{p:'#0277BD',s:'#E1F5FE',a:'#4FC3F7',b:'#F7FDFF',t:'#0A1A2A'}},{id:'retail-comic',pf:['comic-shop'],n:'Comic Shop',c:{p:'#311B92',s:'#EDE7F6',a:'#7C4DFF',b:'#F8F6FD',t:'#1A0A3A'}},{id:'retail-outdoor',pf:['outdoor-store'],n:'Outdoor Gear',c:{p:'#1B5E20',s:'#E8F5E9',a:'#FF8F00',b:'#F7FDF7',t:'#0A2A0A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'retail',t.pf,t.n,t.c)),

  // EVENTS (12)
  ...([{id:'events-wedding',pf:['wedding-planner'],n:'Wedding Planner',c:{p:'#D4A0C4',s:'#FDF2F8',a:'#E8B4B8',b:'#FEFBFD',t:'#4A2A3A'}},{id:'events-corporate',pf:['corporate-events'],n:'Corporate Events',c:{p:'#1D3557',s:'#E8EDF5',a:'#A8DADC',b:'#F8FAFD',t:'#0A1A2E'}},{id:'events-birthday',pf:['party-planner'],n:'Party Planner',c:{p:'#FF6F00',s:'#FFF3E0',a:'#FFB74D',b:'#FFFBF7',t:'#3A1A00'}},{id:'events-conference',pf:['conference-planner'],n:'Conference',c:{p:'#0D47A1',s:'#E3F2FD',a:'#42A5F5',b:'#F8FBFE',t:'#0A1A2A'}},{id:'events-venue',pf:['event-venue'],n:'Event Venue',c:{p:'#5D4037',s:'#EFEBE9',a:'#8D6E63',b:'#FAF8F7',t:'#2A1A0A'}},{id:'events-catering',pf:['event-catering'],n:'Event Catering',c:{p:'#D84315',s:'#FBE9E7',a:'#FF8A65',b:'#FDF8F6',t:'#2A1000'}},{id:'events-dj',pf:['dj'],n:'DJ Services',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#E91E63',b:'#FAFAFA',t:'#0A0A0A'}},{id:'events-photobooth',pf:['photobooth-rental'],n:'Photo Booth',c:{p:'#7B1FA2',s:'#F3E5F5',a:'#BA68C8',b:'#FDF8FE',t:'#2A0A4A'}},{id:'events-florist',pf:['event-florist'],n:'Event Florist',c:{p:'#E91E63',s:'#FCE4EC',a:'#81C784',b:'#FDFAFC',t:'#2A0A1A'}},{id:'events-rental',pf:['event-rental'],n:'Event Rentals',c:{p:'#455A64',s:'#ECEFF1',a:'#90A4AE',b:'#FAFAFA',t:'#1A1A1A'}},{id:'events-balloon',pf:['balloon-artist'],n:'Balloon Artist',c:{p:'#D81B60',s:'#FCE4EC',a:'#FFB74D',b:'#FDFAFC',t:'#3A0A2A'}},{id:'events-planner',pf:['event-planner'],n:'Event Planner',c:{p:'#6A1B9A',s:'#F3E5F5',a:'#BA68C8',b:'#FDFAFE',t:'#2A0A4A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'events',t.pf,t.n,t.c)),

  // CHILDCARE (10)
  ...([{id:'childcare-daycare',pf:['daycare'],n:'Daycare Center',c:{p:'#FF6B6B',s:'#FFF0F0',a:'#FFD93D',b:'#FFFBFB',t:'#4A0A0A'}},{id:'childcare-preschool',pf:['preschool'],n:'Preschool',c:{p:'#4FC3F7',s:'#E1F5FE',a:'#FFB74D',b:'#F7FDFF',t:'#0A1A2A'}},{id:'childcare-nanny',pf:['nanny-agency'],n:'Nanny Agency',c:{p:'#6B8F71',s:'#EAF2EB',a:'#C4A87C',b:'#F9FBF9',t:'#2A3A2A'}},{id:'childcare-tutoring',pf:['tutoring-center'],n:'Tutoring Center',c:{p:'#5C6BC0',s:'#E8EAF6',a:'#FF7043',b:'#F8F9FD',t:'#1A1A3A'}},{id:'childcare-montessori',pf:['montessori-school'],n:'Montessori',c:{p:'#8D6E63',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#2A1A0A'}},{id:'childcare-afterschool',pf:['after-school'],n:'After School',c:{p:'#7B1FA2',s:'#F3E5F5',a:'#FFB74D',b:'#FDF8FE',t:'#2A0A4A'}},{id:'childcare-summer',pf:['summer-camp'],n:'Summer Camp',c:{p:'#2E7D32',s:'#E8F5E9',a:'#FF8F00',b:'#F7FDF7',t:'#0A2A0A'}},{id:'childcare-music',pf:['children-music'],n:'Music Class',c:{p:'#E91E63',s:'#FCE4EC',a:'#FFD54F',b:'#FEFAFC',t:'#2A0A1A'}},{id:'childcare-art',pf:['children-art'],n:'Art Class',c:{p:'#FF8F00',s:'#FFF8E1',a:'#E91E63',b:'#FFFEFA',t:'#3A2000'}},{id:'childcare-special',pf:['special-needs'],n:'Special Needs',c:{p:'#00897B',s:'#E0F2F1',a:'#80CBC4',b:'#F7FDFC',t:'#0A2A20'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'childcare',t.pf,t.n,t.c)),

  // PET (9)
  ...([{id:'pet-grooming',pf:['pet-groomer'],n:'Pet Grooming',c:{p:'#6D4C41',s:'#EFEBE9',a:'#FF8F00',b:'#FAF8F7',t:'#2A1A0A'}},{id:'pet-vet',pf:['veterinarian'],n:'Veterinary',c:{p:'#1B5E20',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'pet-daycare',pf:['pet-daycare'],n:'Pet Daycare',c:{p:'#FF6F00',s:'#FFF3E0',a:'#FFB74D',b:'#FFFBF7',t:'#3A1A00'}},{id:'pet-training',pf:['dog-trainer'],n:'Dog Training',c:{p:'#E65100',s:'#FFF3E0',a:'#FF9800',b:'#FFFBF7',t:'#3A1A00'}},{id:'pet-boarding',pf:['pet-boarding'],n:'Pet Boarding',c:{p:'#5D4037',s:'#EFEBE9',a:'#8D6E63',b:'#FAF8F7',t:'#2A1A0A'}},{id:'pet-walking',pf:['dog-walker'],n:'Dog Walking',c:{p:'#2E7D32',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'pet-sitting',pf:['pet-sitter'],n:'Pet Sitting',c:{p:'#6B8F71',s:'#EAF2EB',a:'#C4A87C',b:'#F9FBF9',t:'#2A3A2A'}},{id:'pet-supply',pf:['pet-supply'],n:'Pet Supply',c:{p:'#0277BD',s:'#E1F5FE',a:'#4FC3F7',b:'#F7FDFF',t:'#0A1A2A'}},{id:'pet-aquatics',pf:['aquarium-store'],n:'Aquatics',c:{p:'#00838F',s:'#E0F7FA',a:'#4DD0E1',b:'#F7FDFE',t:'#0A2A3A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'pet',t.pf,t.n,t.c)),

  // TRAVEL (8)
  ...([{id:'travel-agency',pf:['travel-agent'],n:'Travel Agency',c:{p:'#0277BD',s:'#E1F5FE',a:'#FFB74D',b:'#F7FDFF',t:'#0A1A2A'}},{id:'travel-tour',pf:['tour-operator'],n:'Tour Operator',c:{p:'#2E7D32',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'travel-hotel',pf:['hotel','inn'],n:'Hotel',c:{p:'#5D4037',s:'#EFEBE9',a:'#D4AF37',b:'#FAF8F7',t:'#2A1A0A'}},{id:'travel-bnb',pf:['airbnb-host'],n:'Vacation Rental',c:{p:'#E91E63',s:'#FCE4EC',a:'#F48FB1',b:'#FEFAFC',t:'#2A0A1A'}},{id:'travel-guide',pf:['tour-guide'],n:'Tour Guide',c:{p:'#FF6F00',s:'#FFF3E0',a:'#FFB74D',b:'#FFFBF7',t:'#3A1A00'}},{id:'travel-adventure',pf:['adventure-travel'],n:'Adventure',c:{p:'#D84315',s:'#FBE9E7',a:'#FF8A65',b:'#FDF8F6',t:'#2A1000'}},{id:'travel-luxury',pf:['luxury-travel'],n:'Luxury Travel',c:{p:'#1A1A1A',s:'#F5F5F5',a:'#D4AF37',b:'#FAFAFA',t:'#0A0A0A'}},{id:'travel-cruise',pf:['cruise-agent'],n:'Cruise Specialist',c:{p:'#0D47A1',s:'#E3F2FD',a:'#42A5F5',b:'#F8FBFE',t:'#0A1A2A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'travel',t.pf,t.n,t.c)),

  // TECH (10)
  ...([{id:'tech-startup',pf:['startup','saas'],n:'Startup',c:{p:'#1A1A1A',s:'#F0F0F0',a:'#00E676',b:'#FAFAFA',t:'#0A0A0A'}},{id:'tech-ai',pf:['ai-company'],n:'AI Company',c:{p:'#311B92',s:'#EDE7F6',a:'#7C4DFF',b:'#F8F6FD',t:'#1A0A3A'}},{id:'tech-dev',pf:['dev-agency'],n:'Dev Agency',c:{p:'#1565C0',s:'#E3F2FD',a:'#FF5722',b:'#F8FBFE',t:'#0A1A3A'}},{id:'tech-cyber',pf:['cybersecurity'],n:'Cybersecurity',c:{p:'#1A1A1A',s:'#E8E8E8',a:'#00BCD4',b:'#F8F8F8',t:'#0A0A0A'}},{id:'tech-cloud',pf:['cloud-consultant'],n:'Cloud Consulting',c:{p:'#0D47A1',s:'#E3F2FD',a:'#42A5F5',b:'#F8FBFE',t:'#0A1A2A'}},{id:'tech-it',pf:['it-services'],n:'IT Services',c:{p:'#37474F',s:'#ECEFF1',a:'#26C6DA',b:'#FAFAFA',t:'#1A1A1A'}},{id:'tech-mobile',pf:['app-developer'],n:'App Development',c:{p:'#4527A0',s:'#EDE7F6',a:'#FF4081',b:'#F9F8FD',t:'#1A0A3A'}},{id:'tech-data',pf:['data-analytics'],n:'Data Analytics',c:{p:'#00695C',s:'#E0F2F1',a:'#4DB6AC',b:'#F7FDFC',t:'#0A2A20'}},{id:'tech-blockchain',pf:['blockchain-dev'],n:'Blockchain',c:{p:'#FF6F00',s:'#FFF3E0',a:'#FFB74D',b:'#FFFBF7',t:'#3A1A00'}},{id:'tech-iot',pf:['iot-company'],n:'IoT Solutions',c:{p:'#1B5E20',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'tech',t.pf,t.n,t.c)),

  // OFFICES (11)
  ...([{id:'offices-coworking',pf:['coworking-space'],n:'Coworking',c:{p:'#37474F',s:'#ECEFF1',a:'#FF5722',b:'#FAFAFA',t:'#1A1A1A'}},{id:'offices-dental',pf:['dental-office'],n:'Dental Office',c:{p:'#006D77',s:'#E0F0F0',a:'#FFDDD2',b:'#FFFFFF',t:'#1A1A1A'}},{id:'offices-medical',pf:['medical-office'],n:'Medical Office',c:{p:'#1B6B93',s:'#E6F0F7',a:'#4FC3F7',b:'#F7FBFD',t:'#0A2A3A'}},{id:'offices-law',pf:['law-office'],n:'Law Office',c:{p:'#283593',s:'#E8EAF6',a:'#7986CB',b:'#F8F9FD',t:'#0A0A2A'}},{id:'offices-therapy',pf:['therapy-office'],n:'Therapy Office',c:{p:'#6B8F71',s:'#EAF2EB',a:'#C4A87C',b:'#F9FBF9',t:'#2A3A2A'}},{id:'offices-realestate',pf:['real-estate-office'],n:'Real Estate Office',c:{p:'#1B5E20',s:'#E8F5E9',a:'#FF8F00',b:'#F7FDF7',t:'#0A2A0A'}},{id:'offices-financial',pf:['financial-office'],n:'Financial Office',c:{p:'#1D3557',s:'#E8EDF5',a:'#D4AF37',b:'#F7FAFD',t:'#0A1A2E'}},{id:'offices-architect',pf:['architecture-firm'],n:'Architecture Firm',c:{p:'#455A64',s:'#ECEFF1',a:'#FF7043',b:'#FAFAFA',t:'#1A1A1A'}},{id:'offices-consulting',pf:['consulting-firm'],n:'Consulting Firm',c:{p:'#0D47A1',s:'#E3F2FD',a:'#FFB300',b:'#F8FBFE',t:'#0A1A2A'}},{id:'offices-insurance',pf:['insurance-office'],n:'Insurance Office',c:{p:'#1565C0',s:'#E3F2FD',a:'#64B5F6',b:'#F8FBFE',t:'#0A1A3A'}},{id:'offices-nonprofit',pf:['nonprofit'],n:'Nonprofit',c:{p:'#2E7D32',s:'#E8F5E9',a:'#FF8F00',b:'#F7FDF7',t:'#0A2A0A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'offices',t.pf,t.n,t.c)),

  // SPECIALTY (10)
  ...([{id:'specialty-astrology',pf:['astrologer'],n:'Astrology',c:{p:'#311B92',s:'#EDE7F6',a:'#D4AF37',b:'#F8F6FD',t:'#1A0A3A'}},{id:'specialty-tarot',pf:['tarot-reader'],n:'Tarot Reading',c:{p:'#4A148C',s:'#F3E5F5',a:'#CE93D8',b:'#FDF8FE',t:'#2A0A4A'}},{id:'specialty-hypnosis',pf:['hypnotherapist'],n:'Hypnotherapy',c:{p:'#00695C',s:'#E0F2F1',a:'#80CBC4',b:'#F7FDFC',t:'#0A2A20'}},{id:'specialty-nutrition',pf:['nutritionist'],n:'Nutritionist',c:{p:'#2E7D32',s:'#E8F5E9',a:'#81C784',b:'#F7FDF7',t:'#0A2A0A'}},{id:'specialty-meditation',pf:['meditation-teacher'],n:'Meditation',c:{p:'#5C6BC0',s:'#E8EAF6',a:'#9FA8DA',b:'#F8F9FD',t:'#1A1A3A'}},{id:'specialty-reiki',pf:['reiki-practitioner'],n:'Reiki Healing',c:{p:'#7B1FA2',s:'#F3E5F5',a:'#BA68C8',b:'#FDF8FE',t:'#2A0A4A'}},{id:'specialty-fengshui',pf:['feng-shui-consultant'],n:'Feng Shui',c:{p:'#D84315',s:'#FBE9E7',a:'#FFAB40',b:'#FDF8F6',t:'#2A1000'}},{id:'specialty-crystal',pf:['crystal-healer'],n:'Crystal Healing',c:{p:'#8E24AA',s:'#F3E5F5',a:'#D4A0C4',b:'#FDF8FE',t:'#2A0A4A'}},{id:'specialty-organizer',pf:['professional-organizer'],n:'Home Organizer',c:{p:'#6D4C41',s:'#EFEBE9',a:'#A1887F',b:'#FAF8F7',t:'#2A1A0A'}},{id:'specialty-notary',pf:['notary'],n:'Notary Public',c:{p:'#37474F',s:'#ECEFF1',a:'#90A4AE',b:'#FAFAFA',t:'#1A1A1A'}}] as Array<{id:string;pf:string[];n:string;c:ShorthandColors}>).map(t=>tpl(t.id,'specialty',t.pf,t.n,t.c)),
];

// =============================================================================
// Template factory — generates full TemplateDefinition from compact data
// =============================================================================

type ShorthandColors = { p: string; s: string; a: string; b: string; t: string };

function colorsFromShorthand(c: ShorthandColors): TemplateDefinition['colors'] {
  return { primary: c.p, secondary: c.s, accent: c.a, background: c.b, text: c.t };
}

function tpl(id: string, industry: string, pf: string[], name: string, c: ShorthandColors): TemplateDefinition {
  return templateDef(id, industry, pf, name, colorsFromShorthand(c));
}

function templateDef(
  id: string, industry: string, professionTypes: string[], name: string,
  colors: TemplateDefinition['colors'],
): TemplateDefinition {
  const sections = defaultSections(industry);
  return {
    id, name, industry, professionTypes,
    sections,
    colors,
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: { maxWidth: 'wide', headerStyle: 'centered', navStyle: 'sticky' },
  };
}

function defaultSections(industry: string): TemplateDefinition['sections'] {
  const base: TemplateDefinition['sections'] = [
    { type: 'hero', config: { fullScreen: true, overlayOpacity: 0.3, showBadge: true } },
    { type: 'about', config: { layout: 'split', showPhoto: true, showCredentials: true } },
    { type: 'gallery', config: { columns: 3, gap: 'sm', lightbox: true } },
  ];

  const services: TemplateDefinition['sections'] = [
    { type: 'services', config: { layout: 'cards', columns: 3 } },
  ];

  if (['photography', 'coaching', 'teaching', 'legal', 'medical', 'beauty', 'fitness', 'home-services', 'tech', 'offices', 'specialty'].includes(industry)) {
    return [...base, ...services,
      { type: 'pricing', config: { layout: 'tiers', columns: 3, highlightMiddle: true } },
      { type: 'testimonials', config: { layout: 'carousel' } },
      { type: 'contact', config: { layout: 'split', showMap: false } },
    ];
  }

  if (['restaurant', 'retail', 'events', 'childcare', 'pet', 'travel', 'real-estate'].includes(industry)) {
    return [...base, ...services,
      { type: 'testimonials', config: { layout: 'grid', columns: 2 } },
      { type: 'contact', config: { layout: 'split', showMap: true, showHours: true } },
    ];
  }

  if (['creative', 'marketing', 'influencer'].includes(industry)) {
    return [...base,
      { type: 'services', config: { layout: 'list', columns: 1 } },
      { type: 'testimonials', config: { layout: 'carousel' } },
      { type: 'contact', config: { layout: 'centered' } },
    ];
  }

  return [...base, ...services,
    { type: 'testimonials', config: { layout: 'grid', columns: 2 } },
    { type: 'contact', config: { layout: 'split', showMap: false } },
  ];
}
