import { json } from "../lib/response"; import { requireAuth, requireRole } from "../lib/auth";

export async function onRequestPost(context: { request: Request; env: { DB?: D1Database; JWT_SECRET?: string; ENVIRONMENT?: string; DEEPSEEK_API_KEY?: string } }): Promise<Response> {
  try { const body = await context.request.json() as { name: string; email: string; website?: string; serviceArea?: string; bio?: string }; if (!body.name || !body.email) return json({ error: "Name and email are required." }, 400); const db = context.env.DB!; const existing = await db.prepare("SELECT id FROM photographers WHERE email = ?").bind(body.email).first(); if (existing) return json({ error: "This email has already applied." }, 409); const id = crypto.randomUUID(); await db.prepare("INSERT INTO photographers (id, name, email, website, portfolio_url, service_area, bio, status) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')").bind(id, body.name, body.email, body.website ?? null, body.website ?? null, body.serviceArea ?? null, body.bio ?? null).run(); return json({ success: true, id }, 201); } catch (err) { console.error("Photographer apply error:", err); return json({ error: "Something went wrong." }, 500); }
}
export async function onRequestGet(context: { request: Request; env: { DB?: D1Database; JWT_SECRET?: string; ENVIRONMENT?: string; DEEPSEEK_API_KEY?: string } }): Promise<Response> {
  try { const a = await requireAuth(context.request, context.env); if (a instanceof Response) return a; const rc = requireRole(a, "platform_owner"); if (rc) return rc; const r = await context.env.DB!.prepare("SELECT id, name, email, website, portfolio_url, service_area, bio, status, slug, specialties, tagline, verified, featured, created_at FROM photographers ORDER BY created_at DESC").all(); return json({ photographers: r.results ?? [] }); } catch (err) { console.error("List photographers error:", err); return json({ error: "Something went wrong." }, 500); }
}
export async function onRequestPut(context: { request: Request; env: { DB?: D1Database; JWT_SECRET?: string; ENVIRONMENT?: string; DEEPSEEK_API_KEY?: string } }): Promise<Response> {
  try { const a = await requireAuth(context.request, context.env); if (a instanceof Response) return a; const rc = requireRole(a, "platform_owner"); if (rc) return rc; const body = await context.request.json() as { id: string; status?: string; verified?: boolean; featured?: boolean; slug?: string; tagline?: string }; if (!body.id) return json({ error: "ID is required" }, 400); if (body.status !== undefined && !["pending","approved","rejected"].includes(body.status)) return json({ error: "Valid status is required" }, 400); if (body.slug !== undefined) { if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(body.slug)) return json({ error: "Invalid slug format" }, 400); const existing = await context.env.DB!.prepare("SELECT id FROM photographers WHERE slug = ? AND id != ?").bind(body.slug, body.id).first(); if (existing) return json({ error: "Slug already taken" }, 409); } if (body.tagline !== undefined && body.tagline.length >= 200) return json({ error: "Tagline must be under 200 characters" }, 400); const parts: string[] = []; const vals: any[] = []; if (body.status !== undefined) { parts.push("status = ?"); vals.push(body.status); } if (body.verified !== undefined) { parts.push("verified = ?"); vals.push(body.verified ? 1 : 0); parts.push("verified_at = ?"); vals.push(body.verified ? new Date().toISOString() : null); } if (body.featured !== undefined) { parts.push("featured = ?"); vals.push(body.featured ? 1 : 0); } if (body.slug !== undefined) { parts.push("slug = ?"); vals.push(body.slug); } if (body.tagline !== undefined) { parts.push("tagline = ?"); vals.push(body.tagline); } if (parts.length === 0) return json({ error: "No fields to update" }, 400); vals.push(body.id); await context.env.DB!.prepare(`UPDATE photographers SET ${parts.join(", ")} WHERE id = ?`).bind(...vals).run(); return json({ success: true }); } catch (err) { console.error("Update photographer error:", err); return json({ error: "Something went wrong." }, 500); }
}
