import { json } from "../lib/response"; import { requireAuth, requireRole } from "../lib/auth";

export async function onRequestPost(context: { request: Request; env: { DB?: D1Database } }): Promise<Response> {
  try { const body = await context.request.json() as { name: string; email: string; website?: string; serviceArea?: string; bio?: string }; if (!body.name || !body.email) return json({ error: "Name and email are required." }, 400); const db = context.env.DB!; const existing = await db.prepare("SELECT id FROM photographers WHERE email = ?").bind(body.email).first(); if (existing) return json({ error: "This email has already applied." }, 409); const id = crypto.randomUUID(); await db.prepare("INSERT INTO photographers (id, name, email, website, portfolio_url, service_area, bio, status) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')").bind(id, body.name, body.email, body.website ?? null, body.website ?? null, body.serviceArea ?? null, body.bio ?? null).run(); return json({ success: true, id }, 201); } catch (err) { console.error("Photographer apply error:", err); return json({ error: "Something went wrong." }, 500); }
}
export async function onRequestGet(context: { request: Request; env: { DB?: D1Database } }): Promise<Response> {
  try { const a = await requireAuth(context.request, context.env); if ("error" in a) return a; const rc = requireRole(a, "platform_owner"); if (rc) return rc; const r = await context.env.DB!.prepare("SELECT * FROM photographers ORDER BY created_at DESC").all(); return json({ photographers: r.results ?? [] }); } catch (err) { console.error("List photographers error:", err); return json({ error: "Something went wrong." }, 500); }
}
export async function onRequestPut(context: { request: Request; env: { DB?: D1Database } }): Promise<Response> {
  try { const a = await requireAuth(context.request, context.env); if ("error" in a) return a; const rc = requireRole(a, "platform_owner"); if (rc) return rc; const body = await context.request.json() as { id: string; status: string }; if (!body.id || !["pending","approved","rejected"].includes(body.status)) return json({ error: "Valid id and status are required" }, 400); await context.env.DB!.prepare("UPDATE photographers SET status = ? WHERE id = ?").bind(body.status, body.id).run(); return json({ success: true }); } catch (err) { console.error("Update photographer error:", err); return json({ error: "Something went wrong." }, 500); }
}
