import { json } from "../../lib/response"; import { requireAuth, requireRole } from "../../lib/auth";

export async function onRequestGet(context: { request: Request; env: { DB?: D1Database; JWT_SECRET?: string; ENVIRONMENT?: string; DEEPSEEK_API_KEY?: string } }): Promise<Response> {
  try { const a = await requireAuth(context.request, context.env); if (a instanceof Response) return a; const rc = requireRole(a, "platform_owner"); if (rc) return rc; const db = context.env.DB!; const r = await db.prepare("SELECT * FROM ad_tiles ORDER BY position ASC").all(); const ads = (r.results ?? []).map((x: Record<string,unknown>) => ({ id: x.id, imageUrl: x.image_url ?? null, linkUrl: x.link_url ?? null, message: x.message ?? null, position: x.position, active: x.active === 1, createdAt: x.created_at })); return json({ ads }); } catch (err) { console.error("Admin list ads error:", err); return json({ error: "Something went wrong" }, 500); }
}
export async function onRequestPost(context: { request: Request; env: { DB?: D1Database; JWT_SECRET?: string; ENVIRONMENT?: string; DEEPSEEK_API_KEY?: string } }): Promise<Response> {
  try { const a = await requireAuth(context.request, context.env); if (a instanceof Response) return a; const rc = requireRole(a, "platform_owner"); if (rc) return rc; const body = await context.request.json() as { imageUrl?: string; linkUrl?: string; message?: string; position?: number; active?: boolean }; const db = context.env.DB!; const id = crypto.randomUUID(); let pos = body.position ?? 1; if (!body.position) { const m = await db.prepare("SELECT MAX(position) as max_pos FROM ad_tiles").first<{max_pos:number|null}>(); pos = (m?.max_pos ?? 0) + 1; } await db.prepare("INSERT INTO ad_tiles (id, image_url, link_url, message, position, active) VALUES (?, ?, ?, ?, ?, ?)").bind(id, body.imageUrl ?? null, body.linkUrl ?? null, body.message ?? null, pos, body.active !== false ? 1 : 0).run(); return json({ ad: { id, imageUrl: body.imageUrl ?? null, linkUrl: body.linkUrl ?? null, message: body.message ?? null, position: pos, active: body.active !== false } }, 201); } catch (err) { console.error("Create ad error:", err); return json({ error: "Something went wrong" }, 500); }
}
export async function onRequestPut(context: { request: Request; env: { DB?: D1Database; JWT_SECRET?: string; ENVIRONMENT?: string; DEEPSEEK_API_KEY?: string } }): Promise<Response> {
  try { const a = await requireAuth(context.request, context.env); if (a instanceof Response) return a; const rc = requireRole(a, "platform_owner"); if (rc) return rc; const body = await context.request.json() as { id: string; imageUrl?: string; linkUrl?: string; message?: string; position?: number; active?: boolean }; if (!body.id) return json({ error: "Ad ID is required" }, 400); const db = context.env.DB!; const parts: string[] = []; const values: (string|number|null)[] = []; if (body.imageUrl !== undefined) { parts.push("image_url = ?"); values.push(body.imageUrl ?? null); } if (body.linkUrl !== undefined) { parts.push("link_url = ?"); values.push(body.linkUrl ?? null); } if (body.message !== undefined) { parts.push("message = ?"); values.push(body.message ?? null); } if (body.position !== undefined) { parts.push("position = ?"); values.push(body.position); } if (body.active !== undefined) { parts.push("active = ?"); values.push(body.active ? 1 : 0); } if (parts.length > 0) { values.push(body.id); await db.prepare(`UPDATE ad_tiles SET ${parts.join(", ")} WHERE id = ?`).bind(...(values as [string|number|null])).run(); } return json({ success: true }); } catch (err) { console.error("Update ad error:", err); return json({ error: "Something went wrong" }, 500); }
}
export async function onRequestDelete(context: { request: Request; env: { DB?: D1Database; JWT_SECRET?: string; ENVIRONMENT?: string; DEEPSEEK_API_KEY?: string } }): Promise<Response> {
  try { const a = await requireAuth(context.request, context.env); if (a instanceof Response) return a; const rc = requireRole(a, "platform_owner"); if (rc) return rc; const url = new URL(context.request.url); const adId = url.searchParams.get("id"); if (!adId) return json({ error: "Ad ID is required" }, 400); await context.env.DB!.prepare("DELETE FROM ad_tiles WHERE id = ?").bind(adId).run(); return json({ success: true }); } catch (err) { console.error("Delete ad error:", err); return json({ error: "Something went wrong" }, 500); }
}
